=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersDeValidation/modules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="modules">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="module" maxOccurs="12" minOccurs="12">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="Code" type="xs:string"/>
          <xs:element name="Name" type="xs:string"/>
          <xs:element name="chefModule" type="xs:string"/>
          <xs:element name="ElementName" type="xs:string" maxOccurs="3" minOccurs="1"/>
          <xs:element name="Dept_Attachement" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/modules_AP2.xml
<?xml version="1.0"?>
<modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/modules.xsd">
  <module>
    <Code>AP31</Code>
    <Name>pede. Suspendisse dui.</Name>
    <ChefModule>EL Haddad</ChefModule>
    <ElementName>Nullam feugiat placerat</ElementName>
    <ElementName>varius et, euismod</ElementName>
  </module>
  <module>
    <Code>AP32</Code>
    <Name>a nunc. In</Name>
    <ChefModule>Badir</ChefModule>
    <ElementName>sodales nisi magna</ElementName>
    <ElementName>elementum sem, vitae</ElementName>
  </module>
  <module>
    <Code>AP33</Code>
    <Name>amet metus. Aliquam</Name>
    <ChefModule>Ezzine</ChefModule>
    <ElementName>Cras vulputate velit</ElementName>
    <ElementName>scelerisque neque sed</ElementName>
  </module>
  <module>
    <Code>AP34</Code>
    <Name>quam vel sapien</Name>
    <ChefModule>El Alami Hassoun</ChefModule>
    <ElementName>Nunc mauris elit,</ElementName>
    <ElementName>libero et tristique</ElementName>
  </module>
  <module>
    <Code>AP35</Code>
    <Name>feugiat nec, diam.</Name>
    <ChefModule>Lazaar</ChefModule>
    <ElementName>pellentesque. Sed dictum.</ElementName>
    <ElementName>ridiculus mus. Proin</ElementName>
  </module>
  <module>
    <Code>AP36</Code>
    <Name>nonummy. Fusce fermentum</Name>
    <ChefModule>El Haddad</ChefModule>
    <ElementName>neque pellentesque massa</ElementName>
    <ElementName>Mauris eu turpis.</ElementName>
  </module>
  <module>
    <Code>AP41</Code>
    <Name>a, arcu. Sed</Name>
    <ChefModule>EL Haddad</ChefModule>
    <ElementName>sit amet risus.</ElementName>
    <ElementName>Nulla facilisi. Sed</ElementName>
  </module>
  <module>
    <Code>AP42</Code>
    <Name>Suspendisse eleifend. Cras</Name>
    <ChefModule>El Alami Hassoun</ChefModule>
    <ElementName>velit dui, semper</ElementName>
    <ElementName>ligula elit, pretium</ElementName>
  </module>
  <module>
    <Code>AP43</Code>
    <Name>ante. Nunc mauris</Name>
    <ChefModule>Badir</ChefModule>
    <ElementName>tortor at risus.</ElementName>
    <ElementName>felis. Donec tempor,</ElementName>
  </module>
  <module>
    <Code>AP44</Code>
    <Name>lobortis quam a</Name>
    <ChefModule>Ezzine</ChefModule>
    <ElementName>euismod est arcu</ElementName>
    <ElementName>ligula eu enim.</ElementName>
  </module>
  <module>
    <Code>AP45</Code>
    <Name>rhoncus. Nullam velit</Name>
    <ChefModule>Ben Achrab</ChefModule>
    <ElementName>ut dolor dapibus</ElementName>
    <ElementName>commodo tincidunt nibh.</ElementName>
  </module>
  <module>
    <Code>AP46</Code>
    <Name>Donec tincidunt. Donec</Name>
    <ChefModule>EL Haddad</ChefModule>
    <ElementName>ornare tortor at</ElementName>
    <ElementName>ac, feugiat non,</ElementName>
  </module>
</modules>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/modules_GINF2.xml
<?xml version="1.0"?>
<modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/modules.xsd">
  <module>
    <Code>GINF31</Code>
    <Name>POO &amp; XML</Name>
    <ChefModule>EL HADDAD</ChefModule>
    <ElementName>Java</ElementName>
    <ElementName>XML</ElementName>
  </module>
  <module>
    <Code>GINF32</Code>
    <Name>Qualit&#xE9; et approche processus</Name>
    <ChefModule>BADIR</ChefModule>
    <ElementName>Assurance Contr&#xF4;le Qualit&#xE9;</ElementName>
    <ElementName> Cycle de vie Logiciel</ElementName>
    <ElementName> Maitrise et Optimisation des processus</ElementName>
  </module>
  <module>
    <Code>GINF33</Code>
    <Name>Mod&#xE9;lisation POO &amp; IHM</Name>
    <ChefModule>EL ALAMI HASSOUN</ChefModule>
    <ElementName>UML</ElementName>
    <ElementName>IHM</ElementName>
  </module>
  <module>
    <Code>GINF34</Code>
    <Name>BD Avanc&#xE9;es I</Name>
    <ChefModule>BADIR</ChefModule>
    <ElementName>Optimisation et Qualit&#xE9; BD</ElementName>
    <ElementName> Administration et Securit&#xE9; BD</ElementName>
    <ElementName> BD Distribu&#xE9;es</ElementName>
  </module>
  <module>
    <Code>GINF35</Code>
    <Name>Administration Et programmation Syst&#xE8;me</Name>
    <ChefModule>EL ALAMI HASSOUN</ChefModule>
    <ElementName>Administration Syst&#xE8;me</ElementName>
    <ElementName> Programmation Syst&#xE8;me</ElementName>
  </module>
  <module>
    <Code>GINF36</Code>
    <Name>Langues et Communication</Name>
    <ChefModule>El Haddad</ChefModule>
    <ElementName>Anglais</ElementName>
    <ElementName> Espagnol</ElementName>
  </module>
  <module>
    <Code>GINF41</Code>
    <Name>Technologies distribu&#xE9;es</Name>
    <ChefModule>EL Haddad</ChefModule>
    <ElementName>J2EE</ElementName>
    <ElementName> C#</ElementName>
  </module>
  <module>
    <Code>GINF42</Code>
    <Name>BD Avanc&#xE9;es II &amp; Cloud</Name>
    <ChefModule>El Alami Hassoun</ChefModule>
    <ElementName>Gestion des donn&#xE9;es Complexes</ElementName>
    <ElementName> NOSQL</ElementName>
    <ElementName> Cloud Computing</ElementName>
  </module>
  <module>
    <Code>GINF43</Code>
    <Name>Traitement de l'image </Name>
    <ChefModule>Badir</ChefModule>
    <ElementName>Traitement d'image</ElementName>
    <ElementName> vision num&#xE9;rique</ElementName>
    <ElementName> Processus stochastique</ElementName>
  </module>
  <module>
    <Code>GINF44</Code>
    <Name>Programmation D&#xE9;clarative et TAV</Name>
    <ChefModule>Ezzine</ChefModule>
    <ElementName>Prog. D&#xE9;clarative</ElementName>
    <ElementName> Technique algorithmique avanc&#xE9;e</ElementName>
  </module>
  <module>
    <Code>GINF45</Code>
    <Name>S&#xE9;curit&#xE9; des syst&#xE8;mes &amp; Cryptographie</Name>
    <ChefModule>Ben Achrab</ChefModule>
    <ElementName>S&#xE9;curit&#xE9; des syst&#xE8;mes</ElementName>
    <ElementName> Cryptographie</ElementName>
  </module>
  <module>
    <Code>GINF46</Code>
    <Name>Management de l'entreprise</Name>
    <ChefModule>EL Haddad</ChefModule>
    <ElementName>Economie &amp; Compta 2</ElementName>
    <ElementName> Projets collectifs</ElementName>
    <ElementName> Management de projet</ElementName>
  </module>
</modules>
