=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersDeValidation/notes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="notes">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="note">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="matiere" maxOccurs="12" minOccurs="12">
              <xs:complexType>
                <xs:attribute name="codeMat" type="xs:string" use="required" />
                 <xs:restriction base="xs:float">
                   <xs:minInclusive value="0"/>
                   <xs:maxInclusive value="20"/>
                  </xs:restriction>
                 </xs:complexType> 
           </xs:element>  
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/notes_G3EI2_apres.xml
<?xml version="1.0"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/notes.xsd">
  <note>
    <CNE>48</CNE>
    <LastName>Valencia</LastName>
    <FirstName>Zanetto</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>49</CNE>
    <LastName>Blondell</LastName>
    <FirstName>Salmoni</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>50</CNE>
    <LastName>Ina</LastName>
    <FirstName>Peake</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>51</CNE>
    <LastName>Philippa</LastName>
    <FirstName>Maxwell</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>52</CNE>
    <LastName>Mackenzie</LastName>
    <FirstName>Claxton</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>53</CNE>
    <LastName>Conan</LastName>
    <FirstName>Lawford</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>54</CNE>
    <LastName>Mackenzie</LastName>
    <FirstName>Coltart</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>55</CNE>
    <LastName>Pren</LastName>
    <FirstName>Sabban</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>56</CNE>
    <LastName>Peg</LastName>
    <FirstName>Dobrowski</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>57</CNE>
    <LastName>Kanya</LastName>
    <FirstName>Gulliver</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>58</CNE>
    <LastName>Marilin</LastName>
    <FirstName>Woodley</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>59</CNE>
    <LastName>Sondra</LastName>
    <FirstName>Haig</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>60</CNE>
    <LastName>Terrye</LastName>
    <FirstName>Arcase</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>61</CNE>
    <LastName>Berry</LastName>
    <FirstName>Hartle</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>62</CNE>
    <LastName>Parrnell</LastName>
    <FirstName>Tinker</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
    <matiere codeMat="G3EI136">12</matiere>
    <matiere codeMat="G3EI141">12</matiere>
    <matiere codeMat="G3EI142">12</matiere>
    <matiere codeMat="G3EI143">12</matiere>
    <matiere codeMat="G3EI144">12</matiere>
    <matiere codeMat="G3EI145">12</matiere>
    <matiere codeMat="G3EI146">12</matiere>
  </note>
  <note>
    <CNE>63</CNE>
    <LastName>Rosy</LastName>
    <FirstName>Maytom</FirstName>
    <matiere codeMat="G3EI131">12</matiere>
    <matiere codeMat="G3EI132">12</matiere>
    <matiere codeMat="G3EI133">12</matiere>
    <matiere codeMat="G3EI134">12</matiere>
    <matiere codeMat="G3EI135">12</matiere>
