=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersDeValidation/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="student" maxOccurs="240" minOccurs="48">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr8.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1115</CNE>
    <LastName>Dabrowski</LastName>
    <FirstName>Gerrie</FirstName>
    <DateofBirth>22/09/2000</DateofBirth>
    <Phone>710 892 2899</Phone>
    <Email>icroydon4o@google.it</Email>
  </student><student>
    <CNE>1116</CNE>
    <LastName>Choat</LastName>
    <FirstName>Gertrud</FirstName>
    <DateofBirth>13/10/1999</DateofBirth>
    <Phone>647 910 1061</Phone>
    <Email>jannwyl4p@tinyurl.com</Email>
  </student><student>
    <CNE>1117</CNE>
    <LastName>Esherwood</LastName>
    <FirstName>Cariotta</FirstName>
    <DateofBirth>14/07/1998</DateofBirth>
    <Phone>226 796 6349</Phone>
    <Email>gtaw4q@dailymail.co.uk</Email>
  </student><student>
    <CNE>1118</CNE>
    <LastName>Fisbey</LastName>
    <FirstName>Mathian</FirstName>
    <DateofBirth>14/04/2000</DateofBirth>
    <Phone>581 703 4564</Phone>
    <Email>emcanellye4r@tinypic.com</Email>
  </student><student>
    <CNE>1119</CNE>
    <LastName>Priest</LastName>
    <FirstName>Lizzie</FirstName>
    <DateofBirth>01/10/2001</DateofBirth>
    <Phone>662 421 3934</Phone>
    <Email>areinhart4s@twitpic.com</Email>
  </student><student>
    <CNE>1120</CNE>
    <LastName>McGarvey</LastName>
    <FirstName>Silvanus</FirstName>
    <DateofBirth>01/01/2000</DateofBirth>
    <Phone>395 513 5263</Phone>
    <Email>emcgauhy4t@naver.com</Email>
  </student><student>
    <CNE>1121</CNE>
    <LastName>Ebbles</LastName>
    <FirstName>Iolanthe</FirstName>
    <DateofBirth>29/05/2001</DateofBirth>
    <Phone>186 742 8819</Phone>
    <Email>smccullen4u@plala.or.jp</Email>
  </student><student>
    <CNE>1122</CNE>
    <LastName>Dunleavy</LastName>
    <FirstName>Darice</FirstName>
    <DateofBirth>23/09/2000</DateofBirth>
    <Phone>318 207 2669</Phone>
    <Email>avanyarkin4v@aboutads.info</Email>
  </student><student>
    <CNE>1123</CNE>
    <LastName>Hallt</LastName>
    <FirstName>Vinni</FirstName>
    <DateofBirth>14/06/2001</DateofBirth>
    <Phone>123 384 6099</Phone>
    <Email>telvin4w@bluehost.com</Email>
  </student><student>
    <CNE>1124</CNE>
    <LastName>Arthars</LastName>
    <FirstName>Johannes</FirstName>
    <DateofBirth>16/04/2001</DateofBirth>
    <Phone>314 683 6492</Phone>
    <Email>cguillon4x@cpanel.net</Email>
  </student><student>
    <CNE>1125</CNE>
    <LastName>Sleaford</LastName>
    <FirstName>Tandi</FirstName>
    <DateofBirth>12/03/2000</DateofBirth>
    <Phone>863 532 0248</Phone>
    <Email>okinnear4y@timesonline.co.uk</Email>
  </student><student>
    <CNE>1126</CNE>
    <LastName>Willison</LastName>
    <FirstName>Renato</FirstName>
    <DateofBirth>22/09/2001</DateofBirth>
    <Phone>717 652 5929</Phone>
    <Email>dcolecrough4z@storify.com</Email>
  </student><student>
    <CNE>1127</CNE>
    <LastName>Theuff</LastName>
    <FirstName>Karyn</FirstName>
    <DateofBirth>26/02/2001</DateofBirth>
    <Phone>115 272 9610</Phone>
    <Email>mmawd50@cbsnews.com</Email>
  </student><student>
    <CNE>1128</CNE>
    <LastName>Charlo</LastName>
    <FirstName>Shirline</FirstName>
    <DateofBirth>09/11/2000</DateofBirth>
    <Phone>199 843 9876</Phone>
    <Email>ameletti51@chron.com</Email>
  </student><student>
    <CNE>1129</CNE>
    <LastName>Rossiter</LastName>
    <FirstName>Teddi</FirstName>
    <DateofBirth>29/04/2001</DateofBirth>
    <Phone>769 864 7604</Phone>
    <Email>cleveritt52@ftc.gov</Email>
  </student><student>
    <CNE>1130</CNE>
    <LastName>Gligori</LastName>
    <FirstName>Jobi</FirstName>
    <DateofBirth>02/06/1998</DateofBirth>
    <Phone>561 515 0313</Phone>
    <Email>wmortel53@utexas.edu</Email>
  </student><student>
    <CNE>1131</CNE>
    <LastName>Kitteringham</LastName>
    <FirstName>Eziechiele</FirstName>
    <DateofBirth>10/01/1998</DateofBirth>
    <Phone>616 525 9957</Phone>
    <Email>shundley54@accuweather.com</Email>
  </student><student>
    <CNE>1132</CNE>
    <LastName>Chaplin</LastName>
    <FirstName>Tam</FirstName>
    <DateofBirth>07/03/2000</DateofBirth>
    <Phone>657 376 7578</Phone>
    <Email>eovitts55@mediafire.com</Email>
  </student><student>
    <CNE>1133</CNE>
    <LastName>Melbourn</LastName>
    <FirstName>Paolo</FirstName>
    <DateofBirth>25/02/1999</DateofBirth>
    <Phone>787 635 9578</Phone>
    <Email>crayment56@stumbleupon.com</Email>
  </student><student>
    <CNE>1134</CNE>
    <LastName>Clowser</LastName>
    <FirstName>Lorri</FirstName>
    <DateofBirth>22/03/2000</DateofBirth>
    <Phone>823 622 8252</Phone>
    <Email>fdaborn57@icq.com</Email>
  </student><student>
    <CNE>1135</CNE>
    <LastName>Cianelli</LastName>
    <FirstName>Teri</FirstName>
    <DateofBirth>20/08/2001</DateofBirth>
    <Phone>767 573 3108</Phone>
    <Email>rruzic58@theatlantic.com</Email>
  </student><student>
    <CNE>1136</CNE>
    <LastName>Houten</LastName>
    <FirstName>Aurelia</FirstName>
    <DateofBirth>22/08/2000</DateofBirth>
    <Phone>409 396 3789</Phone>
    <Email>dlound59@4shared.com</Email>
  </student><student>
    <CNE>1137</CNE>
    <LastName>Checchetelli</LastName>
    <FirstName>Augy</FirstName>
    <DateofBirth>10/04/2000</DateofBirth>
    <Phone>559 183 4046</Phone>
    <Email>nmacpadene5a@youtube.com</Email>
  </student><student>
    <CNE>1138</CNE>
    <LastName>Gagg</LastName>
    <FirstName>Gertrude</FirstName>
    <DateofBirth>22/09/1998</DateofBirth>
    <Phone>968 525 3451</Phone>
    <Email>mkunat5b@globo.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_GINF2_Gr1.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp4/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>18008561</CNE>
    <LastName>AGNAOU&#xA0;</LastName>
    <FirstName>MOHAMED</FirstName>
    <DateofBirth>18/10/1998</DateofBirth>
    <Phone>04 55 28 57 36</Phone>
    <Email>a.ultricies.adipiscing@sagittislobortismauris.com</Email>
  </student><student>
    <CNE>20007924</CNE>
    <LastName>AL ACHKAR&#xA0;</LastName>
    <FirstName>BADR</FirstName>
    <DateofBirth>28/11/1999</DateofBirth>
    <Phone>07 09 95 10 17</Phone>
    <Email>eget@elitpharetra.ca</Email>
  </student><student>
    <CNE>18002613</CNE>
    <LastName>AMARA&#xA0;</LastName>
    <FirstName>ASMAE</FirstName>
    <DateofBirth>29/04/2000</DateofBirth>
    <Phone>04 34 09 21 70</Phone>
    <Email>nonummy@sitamet.com</Email>
  </student><student>
    <CNE>18008851</CNE>
    <LastName>AOUAD&#xA0;</LastName>
    <FirstName>SAMI</FirstName>
    <DateofBirth>21/09/2001</DateofBirth>
    <Phone>04 55 59 07 00</Phone>
    <Email>diam.Sed.diam@dictummagna.net</Email>
  </student><student>
    <CNE>18008461</CNE>
    <LastName>BAHID&#xA0;</LastName>
    <FirstName>RIHAB</FirstName>
    <DateofBirth>31/03/2001</DateofBirth>
    <Phone>09 09 71 13 93</Phone>
    <Email>vel.convallis.in@tellus.edu</Email>
  </student><student>
    <CNE>18012385</CNE>
    <LastName>BARRO&#xA0;</LastName>
    <FirstName>CHEICKNA</FirstName>
    <DateofBirth>18/02/1999</DateofBirth>
    <Phone>04 03 74 96 33</Phone>
    <Email>eu.ligula@Nunc.org</Email>
  </student><student>
    <CNE>18008645</CNE>
    <LastName>BENKHANOUS&#xA0;</LastName>
    <FirstName>SALAHEDDINE</FirstName>
    <DateofBirth>28/04/2001</DateofBirth>
    <Phone>03 65 75 55 99</Phone>
    <Email>dapibus@dapibusgravidaAliquam.com</Email>
  </student><student>
    <CNE>18008723</CNE>
    <LastName>BENTALEB&#xA0;</LastName>
    <FirstName>CHAYMAE</FirstName>
    <DateofBirth>14/09/2000</DateofBirth>
    <Phone>01 13 17 82 27</Phone>
    <Email>In.at@lacusQuisquepurus.edu</Email>
  </student><student>
    <CNE>18008713</CNE>
    <LastName>BOUGUEDDACH&#xA0;</LastName>
    <FirstName>MOHAMED OUSSAMA</FirstName>
    <DateofBirth>31/07/2001</DateofBirth>
    <Phone>01 83 99 82 19</Phone>
    <Email>gravida.molestie.arcu@ac.edu</Email>
  </student><student>
    <CNE>18008663</CNE>
    <LastName>BOUHCAIN&#xA0;</LastName>
    <FirstName>ALI</FirstName>
    <DateofBirth>11/09/2000</DateofBirth>
    <Phone>06 17 06 13 51</Phone>
    <Email>blandit.enim@auctorvelit.com</Email>
  </student><student>
    <CNE>18008572</CNE>
    <LastName>BOUKHALLAD&#xA0;</LastName>
    <FirstName>AISSAME</FirstName>
    <DateofBirth>05/02/2001</DateofBirth>
    <Phone>06 16 17 67 88</Phone>
    <Email>ligula@convallisantelectus.ca</Email>
  </student><student>
    <CNE>17003887</CNE>
    <LastName>CHIHAL&#xA0;</LastName>
    <FirstName>AYA</FirstName>
    <DateofBirth>26/06/2001</DateofBirth>
    <Phone>04 64 98 60 55</Phone>
    <Email>est@laciniaatiaculis.edu</Email>
  </student><student>
    <CNE>18008535</CNE>
    <LastName>DABDOUBI&#xA0;</LastName>
    <FirstName>AYMANE&#xA0;</FirstName>
    <DateofBirth>03/12/2000</DateofBirth>
    <Phone>09 25 82 42 37</Phone>
    <Email>Nulla@nequeInornare.edu</Email>
  </student><student>
    <CNE>18010230</CNE>
    <LastName>DKHISSI&#xA0;</LastName>
    <FirstName>AYOUB</FirstName>
    <DateofBirth>19/07/1999</DateofBirth>
    <Phone>05 77 03 22 28</Phone>
    <Email>a.purus.Duis@semperauctorMauris.org</Email>
  </student><student>
    <CNE>18008842</CNE>
    <LastName>AMARA&#xA0;</LastName>
    <FirstName>ASMAE</FirstName>
    <DateofBirth>27/04/1996</DateofBirth>
    <Phone>09 31 60 34 93</Phone>
    <Email>primis@euismod.net</Email>
  </student><student>
    <CNE>18008829</CNE>
    <LastName>AOUAD&#xA0;</LastName>
    <FirstName>SAMI</FirstName>
    <DateofBirth>19/08/1998</DateofBirth>
    <Phone>02 41 34 61 92</Phone>
    <Email>eu.tellus.eu@urnaet.org</Email>
  </student><student>
    <CNE>17004775</CNE>
    <LastName>BAHID&#xA0;</LastName>
    <FirstName>RIHAB</FirstName>
    <DateofBirth>08/01/2001</DateofBirth>
    <Phone>01 51 56 04 75</Phone>
    <Email>Cras.interdum.Nunc@nec.net</Email>
  </student><student>
    <CNE>18008745</CNE>
    <LastName>BARRO&#xA0;</LastName>
    <FirstName>CHEICKNA</FirstName>
    <DateofBirth>18/03/1995</DateofBirth>
    <Phone>09 86 03 83 03</Phone>
    <Email>aliquam.eros.turpis@Maurisquisturpis.org</Email>
  </student><student>
    <CNE>16010196</CNE>
    <LastName>BEN TARKI&#xA0;</LastName>
    <FirstName>NOUHAILA</FirstName>
    <DateofBirth>01/02/2000</DateofBirth>
    <Phone>02 05 53 81 64</Phone>
    <Email>fringilla.cursus.purus@turpisnonenim.net</Email>
  </student><student>
    <CNE>17005920</CNE>
    <LastName>BENKHANOUS&#xA0;</LastName>
    <FirstName>SALAHEDDINE</FirstName>
    <DateofBirth>31/12/1998</DateofBirth>
    <Phone>03 60 13 08 48</Phone>
    <Email>pretium.et@Aeneanegestas.edu</Email>
  </student><student>
    <CNE>18008470</CNE>
    <LastName>BENTALEB&#xA0;</LastName>
    <FirstName>CHAYMAE</FirstName>
    <DateofBirth>15/01/2001</DateofBirth>
    <Phone>05 19 05 86 31</Phone>
    <Email>ornare.facilisis.eget@elit.ca</Email>
  </student><student>
    <CNE>18008836</CNE>
    <LastName>EL MOUTTAKI&#xA0;</LastName>
    <FirstName>ADNAN</FirstName>
    <DateofBirth>29/04/1998</DateofBirth>
    <Phone>01 75 51 34 37</Phone>
    <Email>ante@orci.net</Email>
  </student><student>
    <CNE>18008738</CNE>
    <LastName>EN-NABOUCH&#xA0;</LastName>
    <FirstName>MOHAMED</FirstName>
    <DateofBirth>09/04/1999</DateofBirth>
    <Phone>01 77 86 71 61</Phone>
    <Email>sodales.Mauris@mattis.ca</Email>
  </student><student>
    <CNE>18008643</CNE>
    <LastName>EN-NIARI&#xA0;</LastName>
    <FirstName>AMR</FirstName>
    <DateofBirth>20/02/1997</DateofBirth>
    <Phone>03 83 03 68 01</Phone>
    <Email>Integer.vitae@eutellusPhasellus.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_G3EI2_Gr2.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>72</CNE>
    <LastName>Grace</LastName>
    <FirstName>Jenman</FirstName>
    <DateofBirth>15/08/1996</DateofBirth>
    <Phone>595 506 9492</Phone>
    <Email>gjenmano@ow.ly</Email>
  </student><student>
    <CNE>73</CNE>
    <LastName>Horton</LastName>
    <FirstName>Fairy</FirstName>
    <DateofBirth>29/07/1995</DateofBirth>
    <Phone>972 281 4353</Phone>
    <Email>hfairyp@shareasale.com</Email>
  </student><student>
    <CNE>74</CNE>
    <LastName>Bobbie</LastName>
    <FirstName>Vian</FirstName>
    <DateofBirth>26/08/2000</DateofBirth>
    <Phone>763 369 4674</Phone>
    <Email>bvianq@icio.us</Email>
  </student><student>
    <CNE>75</CNE>
    <LastName>Minnaminnie</LastName>
    <FirstName>Kemmet</FirstName>
    <DateofBirth>05/04/1996</DateofBirth>
    <Phone>445 233 3401</Phone>
    <Email>mkemmetr@msn.com</Email>
  </student><student>
    <CNE>76</CNE>
    <LastName>Dianne</LastName>
    <FirstName>Pylkynyton</FirstName>
    <DateofBirth>17/03/1997</DateofBirth>
    <Phone>420 190 7904</Phone>
    <Email>dpylkynytons@aol.com</Email>
  </student><student>
    <CNE>77</CNE>
    <LastName>Myranda</LastName>
    <FirstName>Bartholomieu</FirstName>
    <DateofBirth>12/04/1997</DateofBirth>
    <Phone>545 540 0271</Phone>
    <Email>mbartholomieut@latimes.com</Email>
  </student><student>
    <CNE>78</CNE>
    <LastName>Jennine</LastName>
    <FirstName>Briance</FirstName>
    <DateofBirth>16/11/1998</DateofBirth>
    <Phone>875 773 9864</Phone>
    <Email>jbrianceu@adobe.com</Email>
  </student><student>
    <CNE>79</CNE>
    <LastName>Isahella</LastName>
    <FirstName>Gulleford</FirstName>
    <DateofBirth>09/08/2000</DateofBirth>
    <Phone>160 513 4609</Phone>
    <Email>igullefordv@51.la</Email>
  </student><student>
    <CNE>80</CNE>
    <LastName>Fowler</LastName>
    <FirstName>Cattanach</FirstName>
    <DateofBirth>17/06/1997</DateofBirth>
    <Phone>630 373 3262</Phone>
    <Email>fcattanachw@samsung.com</Email>
  </student><student>
    <CNE>81</CNE>
    <LastName>Gage</LastName>
    <FirstName>Marzelli</FirstName>
    <DateofBirth>26/03/1996</DateofBirth>
    <Phone>183 310 9735</Phone>
    <Email>gmarzellix@abc.net.au</Email>
  </student><student>
    <CNE>82</CNE>
    <LastName>Idalia</LastName>
    <FirstName>Titmarsh</FirstName>
    <DateofBirth>16/03/2000</DateofBirth>
    <Phone>788 750 9848</Phone>
    <Email>ititmarshy@thetimes.co.uk</Email>
  </student><student>
    <CNE>83</CNE>
    <LastName>Ham</LastName>
    <FirstName>Meni</FirstName>
    <DateofBirth>17/02/1995</DateofBirth>
    <Phone>205 272 6454</Phone>
    <Email>hmeniz@wp.com</Email>
  </student><student>
    <CNE>84</CNE>
    <LastName>Jess</LastName>
    <FirstName>Randalston</FirstName>
    <DateofBirth>20/03/1996</DateofBirth>
    <Phone>675 738 9968</Phone>
    <Email>jrandalston10@harvard.edu</Email>
  </student><student>
    <CNE>85</CNE>
    <LastName>Emelyne</LastName>
    <FirstName>Tinson</FirstName>
    <DateofBirth>18/06/1999</DateofBirth>
    <Phone>796 884 9163</Phone>
    <Email>etinson11@state.gov</Email>
  </student><student>
    <CNE>86</CNE>
    <LastName>Ynez</LastName>
    <FirstName>Rosengart</FirstName>
    <DateofBirth>27/05/1997</DateofBirth>
    <Phone>448 469 8624</Phone>
    <Email>yrosengart12@booking.com</Email>
  </student><student>
    <CNE>87</CNE>
    <LastName>Erminie</LastName>
    <FirstName>Wilbraham</FirstName>
    <DateofBirth>01/07/1996</DateofBirth>
    <Phone>239 780 5368</Phone>
    <Email>ewilbraham13@unicef.org</Email>
  </student><student>
    <CNE>88</CNE>
    <LastName>Gayler</LastName>
    <FirstName>Arbor</FirstName>
    <DateofBirth>11/11/1996</DateofBirth>
    <Phone>576 336 1450</Phone>
    <Email>garbor14@google.com.hk</Email>
  </student><student>
    <CNE>89</CNE>
    <LastName>Darcee</LastName>
    <FirstName>Sexton</FirstName>
    <DateofBirth>17/12/2000</DateofBirth>
    <Phone>996 218 4408</Phone>
    <Email>dsexton15@geocities.com</Email>
  </student><student>
    <CNE>90</CNE>
    <LastName>Stillmann</LastName>
    <FirstName>Androlli</FirstName>
    <DateofBirth>08/03/2000</DateofBirth>
    <Phone>476 650 4583</Phone>
    <Email>sandrolli16@exblog.jp</Email>
  </student><student>
    <CNE>91</CNE>
    <LastName>Tommy</LastName>
    <FirstName>Rolles</FirstName>
    <DateofBirth>13/02/1996</DateofBirth>
    <Phone>547 440 7861</Phone>
    <Email>trolles17@bloglovin.com</Email>
  </student><student>
    <CNE>92</CNE>
    <LastName>Bennie</LastName>
    <FirstName>Igoe</FirstName>
    <DateofBirth>03/03/1996</DateofBirth>
    <Phone>146 412 2917</Phone>
    <Email>bigoe18@youtu.be</Email>
  </student><student>
    <CNE>93</CNE>
    <LastName>Rosette</LastName>
    <FirstName>Bendall</FirstName>
    <DateofBirth>04/04/2000</DateofBirth>
    <Phone>361 209 9497</Phone>
    <Email>rbendall19@globo.com</Email>
  </student><student>
    <CNE>94</CNE>
    <LastName>Karin</LastName>
    <FirstName>Vasyaev</FirstName>
    <DateofBirth>28/05/1996</DateofBirth>
    <Phone>294 731 4140</Phone>
    <Email>kvasyaev1a@ft.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP2_Gr4.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>779</CNE>
    <LastName>Duplock</LastName>
    <FirstName>Archer</FirstName>
    <DateofBirth>17/12/1999</DateofBirth>
    <Phone>943 759 6918</Phone>
    <Email>dfairbairn20@gov.uk</Email>
  </student><student>
    <CNE>780</CNE>
    <LastName>Castleton</LastName>
    <FirstName>Brennen</FirstName>
    <DateofBirth>10/06/1999</DateofBirth>
    <Phone>715 652 7178</Phone>
    <Email>dteasey21@usa.gov</Email>
  </student><student>
    <CNE>781</CNE>
    <LastName>Pache</LastName>
    <FirstName>Leone</FirstName>
    <DateofBirth>19/02/1999</DateofBirth>
    <Phone>709 613 5542</Phone>
    <Email>mgoulborne22@webeden.co.uk</Email>
  </student><student>
    <CNE>782</CNE>
    <LastName>Oldnall</LastName>
    <FirstName>Panchito</FirstName>
    <DateofBirth>09/05/1998</DateofBirth>
    <Phone>779 338 0137</Phone>
    <Email>vraggitt23@nhs.uk</Email>
  </student><student>
    <CNE>783</CNE>
    <LastName>McGaffey</LastName>
    <FirstName>Claudine</FirstName>
    <DateofBirth>11/03/1999</DateofBirth>
    <Phone>879 769 5059</Phone>
    <Email>blantaph24@imgur.com</Email>
  </student><student>
    <CNE>784</CNE>
    <LastName>Jeness</LastName>
    <FirstName>Leighton</FirstName>
    <DateofBirth>13/06/1999</DateofBirth>
    <Phone>550 432 8767</Phone>
    <Email>dveldstra25@technorati.com</Email>
  </student><student>
    <CNE>785</CNE>
    <LastName>Shoebridge</LastName>
    <FirstName>Raimundo</FirstName>
    <DateofBirth>15/05/2000</DateofBirth>
    <Phone>735 542 7402</Phone>
    <Email>hhanson26@springer.com</Email>
  </student><student>
    <CNE>786</CNE>
    <LastName>Matheson</LastName>
    <FirstName>Aland</FirstName>
    <DateofBirth>04/09/2000</DateofBirth>
    <Phone>677 206 0477</Phone>
    <Email>fsabban27@disqus.com</Email>
  </student><student>
    <CNE>787</CNE>
    <LastName>Attwater</LastName>
    <FirstName>Meridith</FirstName>
    <DateofBirth>18/09/2000</DateofBirth>
    <Phone>826 429 7425</Phone>
    <Email>bheustice28@whitehouse.gov</Email>
  </student><student>
    <CNE>788</CNE>
    <LastName>Heliar</LastName>
    <FirstName>Raye</FirstName>
    <DateofBirth>19/04/2000</DateofBirth>
    <Phone>383 211 8123</Phone>
    <Email>abilfoot29@t.co</Email>
  </student><student>
    <CNE>789</CNE>
    <LastName>Stanistrete</LastName>
    <FirstName>Freda</FirstName>
    <DateofBirth>07/06/2000</DateofBirth>
    <Phone>804 550 7439</Phone>
    <Email>mstiffell2a@irs.gov</Email>
  </student><student>
    <CNE>790</CNE>
    <LastName>Cumbers</LastName>
    <FirstName>Burg</FirstName>
    <DateofBirth>23/01/1999</DateofBirth>
    <Phone>380 250 1878</Phone>
    <Email>kgrundwater2b@jugem.jp</Email>
  </student><student>
    <CNE>791</CNE>
    <LastName>Ferraraccio</LastName>
    <FirstName>Catherine</FirstName>
    <DateofBirth>08/12/1999</DateofBirth>
    <Phone>728 711 6902</Phone>
    <Email>mlownie2c@xinhuanet.com</Email>
  </student><student>
    <CNE>792</CNE>
    <LastName>Chamberlayne</LastName>
    <FirstName>Franklin</FirstName>
    <DateofBirth>24/01/1998</DateofBirth>
    <Phone>713 666 6005</Phone>
    <Email>slaidler2d@mayoclinic.com</Email>
  </student><student>
    <CNE>793</CNE>
    <LastName>Warrington</LastName>
    <FirstName>Darren</FirstName>
    <DateofBirth>02/03/1999</DateofBirth>
    <Phone>174 883 2959</Phone>
    <Email>sdowle2e@hibu.com</Email>
  </student><student>
    <CNE>794</CNE>
    <LastName>Kruger</LastName>
    <FirstName>Haydon</FirstName>
    <DateofBirth>11/04/2000</DateofBirth>
    <Phone>327 902 3992</Phone>
    <Email>bnoulton2f@godaddy.com</Email>
  </student><student>
    <CNE>795</CNE>
    <LastName>Austick</LastName>
    <FirstName>Katlin</FirstName>
    <DateofBirth>05/02/2000</DateofBirth>
    <Phone>302 507 4698</Phone>
    <Email>cshelton2g@alexa.com</Email>
  </student><student>
    <CNE>796</CNE>
    <LastName>David</LastName>
    <FirstName>Velvet</FirstName>
    <DateofBirth>28/10/1999</DateofBirth>
    <Phone>825 713 0056</Phone>
    <Email>cjanks2h@blogspot.com</Email>
  </student><student>
    <CNE>797</CNE>
    <LastName>Sorrel</LastName>
    <FirstName>Chane</FirstName>
    <DateofBirth>26/03/1998</DateofBirth>
    <Phone>305 968 6125</Phone>
    <Email>fburree2i@nymag.com</Email>
  </student><student>
    <CNE>798</CNE>
    <LastName>Milby</LastName>
    <FirstName>Meghann</FirstName>
    <DateofBirth>06/08/2000</DateofBirth>
    <Phone>701 342 7108</Phone>
    <Email>jskippen2j@lulu.com</Email>
  </student><student>
    <CNE>799</CNE>
    <LastName>Finlater</LastName>
    <FirstName>Tawsha</FirstName>
    <DateofBirth>20/03/1999</DateofBirth>
    <Phone>212 776 2589</Phone>
    <Email>ldericot2k@usnews.com</Email>
  </student><student>
    <CNE>800</CNE>
    <LastName>McKean</LastName>
    <FirstName>Edwin</FirstName>
    <DateofBirth>13/10/1999</DateofBirth>
    <Phone>412 556 3039</Phone>
    <Email>kmcaughtrie2l@technorati.com</Email>
  </student><student>
    <CNE>801</CNE>
    <LastName>Jeanel</LastName>
    <FirstName>Ardath</FirstName>
    <DateofBirth>09/08/1998</DateofBirth>
    <Phone>917 391 9027</Phone>
    <Email>kgrombridge2m@marketwatch.com</Email>
  </student><student>
    <CNE>802</CNE>
    <LastName>Wedmore</LastName>
    <FirstName>Slade</FirstName>
    <DateofBirth>10/02/1998</DateofBirth>
    <Phone>596 472 1427</Phone>
    <Email>atallent2n@i2i.jp</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr4.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1019</CNE>
    <LastName>McLeese</LastName>
    <FirstName>Kippie</FirstName>
    <DateofBirth>12/11/1998</DateofBirth>
    <Phone>417 265 8929</Phone>
    <Email>amacpeice20@redcross.org</Email>
  </student><student>
    <CNE>1020</CNE>
    <LastName>Callaby</LastName>
    <FirstName>Homer</FirstName>
    <DateofBirth>03/10/2000</DateofBirth>
    <Phone>866 993 8930</Phone>
    <Email>scurnucke21@altervista.org</Email>
  </student><student>
    <CNE>1021</CNE>
    <LastName>Billison</LastName>
    <FirstName>Mallissa</FirstName>
    <DateofBirth>03/10/1999</DateofBirth>
    <Phone>239 611 4678</Phone>
    <Email>tbourdis22@ibm.com</Email>
  </student><student>
    <CNE>1022</CNE>
    <LastName>Pischel</LastName>
    <FirstName>Batsheva</FirstName>
    <DateofBirth>30/05/2000</DateofBirth>
    <Phone>810 231 3949</Phone>
    <Email>psnap23@cbsnews.com</Email>
  </student><student>
    <CNE>1023</CNE>
    <LastName>Tichelaar</LastName>
    <FirstName>Carlynne</FirstName>
    <DateofBirth>05/09/1999</DateofBirth>
    <Phone>223 436 5625</Phone>
    <Email>santcliffe24@guardian.co.uk</Email>
  </student><student>
    <CNE>1024</CNE>
    <LastName>Farnon</LastName>
    <FirstName>Lorene</FirstName>
    <DateofBirth>15/09/2000</DateofBirth>
    <Phone>372 460 2875</Phone>
    <Email>kbever25@eepurl.com</Email>
  </student><student>
    <CNE>1025</CNE>
    <LastName>Matej</LastName>
    <FirstName>Jayme</FirstName>
    <DateofBirth>08/04/1998</DateofBirth>
    <Phone>423 593 8979</Phone>
    <Email>sgeraud26@miibeian.gov.cn</Email>
  </student><student>
    <CNE>1026</CNE>
    <LastName>Rush</LastName>
    <FirstName>Vinson</FirstName>
    <DateofBirth>22/08/1998</DateofBirth>
    <Phone>713 787 4933</Phone>
    <Email>hgrabeham27@ca.gov</Email>
  </student><student>
    <CNE>1027</CNE>
    <LastName>Witheford</LastName>
    <FirstName>Corrinne</FirstName>
    <DateofBirth>11/12/1999</DateofBirth>
    <Phone>861 772 4705</Phone>
    <Email>rprantoni28@vkontakte.ru</Email>
  </student><student>
    <CNE>1028</CNE>
    <LastName>Lemerle</LastName>
    <FirstName>Riane</FirstName>
    <DateofBirth>23/07/2000</DateofBirth>
    <Phone>993 141 8896</Phone>
    <Email>eantonellini29@dell.com</Email>
  </student><student>
    <CNE>1029</CNE>
    <LastName>Western</LastName>
    <FirstName>Gabriello</FirstName>
    <DateofBirth>26/03/1999</DateofBirth>
    <Phone>715 351 1641</Phone>
    <Email>jhugett2a@cbslocal.com</Email>
  </student><student>
    <CNE>1030</CNE>
    <LastName>Boncore</LastName>
    <FirstName>Gerik</FirstName>
    <DateofBirth>07/06/2000</DateofBirth>
    <Phone>334 887 4902</Phone>
    <Email>opelz2b@dell.com</Email>
  </student><student>
    <CNE>1031</CNE>
    <LastName>Kolakovic</LastName>
    <FirstName>Bliss</FirstName>
    <DateofBirth>02/02/1999</DateofBirth>
    <Phone>653 696 7918</Phone>
    <Email>rlowndsbrough2c@harvard.edu</Email>
  </student><student>
    <CNE>1032</CNE>
    <LastName>Fynan</LastName>
    <FirstName>Brenden</FirstName>
    <DateofBirth>09/05/1999</DateofBirth>
    <Phone>694 430 4510</Phone>
    <Email>tboarleyson2d@aol.com</Email>
  </student><student>
    <CNE>1033</CNE>
    <LastName>Killough</LastName>
    <FirstName>Kippie</FirstName>
    <DateofBirth>25/08/1999</DateofBirth>
    <Phone>689 451 5104</Phone>
    <Email>abeetham2e@smh.com.au</Email>
  </student><student>
    <CNE>1034</CNE>
    <LastName>Flaws</LastName>
    <FirstName>Dian</FirstName>
    <DateofBirth>19/11/2000</DateofBirth>
    <Phone>459 623 3522</Phone>
    <Email>ccrippell2f@artisteer.com</Email>
  </student><student>
    <CNE>1035</CNE>
    <LastName>Fletcher</LastName>
    <FirstName>Roze</FirstName>
    <DateofBirth>30/07/2000</DateofBirth>
    <Phone>460 627 2603</Phone>
    <Email>agaskins2g@blog.com</Email>
  </student><student>
    <CNE>1036</CNE>
    <LastName>Smalridge</LastName>
    <FirstName>Enid</FirstName>
    <DateofBirth>17/02/2000</DateofBirth>
    <Phone>741 129 5463</Phone>
    <Email>rbarriball2h@blinklist.com</Email>
  </student><student>
    <CNE>1037</CNE>
    <LastName>Findlow</LastName>
    <FirstName>Peyter</FirstName>
    <DateofBirth>26/09/1999</DateofBirth>
    <Phone>826 388 5101</Phone>
    <Email>cconelly2i@devhub.com</Email>
  </student><student>
    <CNE>1038</CNE>
    <LastName>Hurlin</LastName>
    <FirstName>Efren</FirstName>
    <DateofBirth>09/11/1998</DateofBirth>
    <Phone>228 219 8703</Phone>
    <Email>astoffers2j@slashdot.org</Email>
  </student><student>
    <CNE>1039</CNE>
    <LastName>Arlt</LastName>
    <FirstName>Fleming</FirstName>
    <DateofBirth>21/09/1998</DateofBirth>
    <Phone>466 743 5890</Phone>
    <Email>bmelato2k@com.com</Email>
  </student><student>
    <CNE>1040</CNE>
    <LastName>Bucknell</LastName>
    <FirstName>Tremayne</FirstName>
    <DateofBirth>02/12/2001</DateofBirth>
    <Phone>890 445 7106</Phone>
    <Email>fbradnocke2l@weebly.com</Email>
  </student><student>
    <CNE>1041</CNE>
    <LastName>Tilte</LastName>
    <FirstName>Caddric</FirstName>
    <DateofBirth>09/11/2000</DateofBirth>
    <Phone>519 200 7839</Phone>
    <Email>jragat2m@diigo.com</Email>
  </student><student>
    <CNE>1042</CNE>
    <LastName>Stormes</LastName>
    <FirstName>Leyla</FirstName>
    <DateofBirth>02/06/1999</DateofBirth>
    <Phone>647 413 6739</Phone>
    <Email>hlegges2n@drupal.org</Email>
  </student></students>
