=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersDeValidation/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="student" maxOccurs="240" minOccurs="48">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr2.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>971</CNE>
    <LastName>Birkmyre</LastName>
    <FirstName>Wilhelmine</FirstName>
    <DateofBirth>10/11/2000</DateofBirth>
    <Phone>674 240 4971</Phone>
    <Email>hcullingfordo@si.edu</Email>
  </student><student>
    <CNE>972</CNE>
    <LastName>Burley</LastName>
    <FirstName>Suzanna</FirstName>
    <DateofBirth>11/12/1998</DateofBirth>
    <Phone>821 187 8952</Phone>
    <Email>erisbridgep@boston.com</Email>
  </student><student>
    <CNE>973</CNE>
    <LastName>Olivelli</LastName>
    <FirstName>Bobinette</FirstName>
    <DateofBirth>13/08/1998</DateofBirth>
    <Phone>865 102 1113</Phone>
    <Email>epetcheyq@symantec.com</Email>
  </student><student>
    <CNE>974</CNE>
    <LastName>Weddeburn</LastName>
    <FirstName>Stinky</FirstName>
    <DateofBirth>06/09/2001</DateofBirth>
    <Phone>729 408 5631</Phone>
    <Email>etwitteyr@theglobeandmail.com</Email>
  </student><student>
    <CNE>975</CNE>
    <LastName>Stiggers</LastName>
    <FirstName>Buckie</FirstName>
    <DateofBirth>30/09/1998</DateofBirth>
    <Phone>762 478 0608</Phone>
    <Email>ngleaves@mashable.com</Email>
  </student><student>
    <CNE>976</CNE>
    <LastName>Lupson</LastName>
    <FirstName>Monte</FirstName>
    <DateofBirth>28/10/2001</DateofBirth>
    <Phone>981 680 6333</Phone>
    <Email>kblakewayt@vimeo.com</Email>
  </student><student>
    <CNE>977</CNE>
    <LastName>Hebble</LastName>
    <FirstName>Salomi</FirstName>
    <DateofBirth>07/01/2001</DateofBirth>
    <Phone>974 202 5801</Phone>
    <Email>awynchu@pinterest.com</Email>
  </student><student>
    <CNE>978</CNE>
    <LastName>Betancourt</LastName>
    <FirstName>Herschel</FirstName>
    <DateofBirth>16/09/2001</DateofBirth>
    <Phone>531 715 5043</Phone>
    <Email>kboostv@goo.ne.jp</Email>
  </student><student>
    <CNE>979</CNE>
    <LastName>Scourge</LastName>
    <FirstName>Walther</FirstName>
    <DateofBirth>09/09/1998</DateofBirth>
    <Phone>342 671 8528</Phone>
    <Email>fkleinplacw@phoca.cz</Email>
  </student><student>
    <CNE>980</CNE>
    <LastName>Phillp</LastName>
    <FirstName>Minne</FirstName>
    <DateofBirth>19/02/2000</DateofBirth>
    <Phone>202 492 7651</Phone>
    <Email>nshordx@accuweather.com</Email>
  </student><student>
    <CNE>981</CNE>
    <LastName>Ensten</LastName>
    <FirstName>Rubia</FirstName>
    <DateofBirth>16/07/1999</DateofBirth>
    <Phone>796 729 6668</Phone>
    <Email>jjanderay@dyndns.org</Email>
  </student><student>
    <CNE>982</CNE>
    <LastName>Pinare</LastName>
    <FirstName>Isaiah</FirstName>
    <DateofBirth>03/07/1998</DateofBirth>
    <Phone>508 415 9829</Phone>
    <Email>tberniniz@gmpg.org</Email>
  </student><student>
    <CNE>983</CNE>
    <LastName>Pimlock</LastName>
    <FirstName>Gilberto</FirstName>
    <DateofBirth>29/03/1998</DateofBirth>
    <Phone>376 434 4825</Phone>
    <Email>trainford10@arizona.edu</Email>
  </student><student>
    <CNE>984</CNE>
    <LastName>Vanderson</LastName>
    <FirstName>Fidela</FirstName>
    <DateofBirth>07/11/2000</DateofBirth>
    <Phone>583 858 5817</Phone>
    <Email>bmennithorp11@adobe.com</Email>
  </student><student>
    <CNE>985</CNE>
    <LastName>Marsham</LastName>
    <FirstName>Nell</FirstName>
    <DateofBirth>12/08/2000</DateofBirth>
    <Phone>597 596 4399</Phone>
    <Email>jrodriguez12@reddit.com</Email>
  </student><student>
    <CNE>986</CNE>
    <LastName>Corringham</LastName>
    <FirstName>Rhett</FirstName>
    <DateofBirth>15/09/2001</DateofBirth>
    <Phone>101 937 4872</Phone>
    <Email>lfarey13@live.com</Email>
  </student><student>
    <CNE>987</CNE>
    <LastName>Stainton - Skinn</LastName>
    <FirstName>Boycey</FirstName>
    <DateofBirth>13/07/2001</DateofBirth>
    <Phone>565 541 6198</Phone>
    <Email>ktuxill14@cyberchimps.com</Email>
  </student><student>
    <CNE>988</CNE>
    <LastName>Trighton</LastName>
    <FirstName>Gelya</FirstName>
    <DateofBirth>27/01/2001</DateofBirth>
    <Phone>977 847 2298</Phone>
    <Email>kausiello15@jugem.jp</Email>
  </student><student>
    <CNE>989</CNE>
    <LastName>Leuty</LastName>
    <FirstName>Henderson</FirstName>
    <DateofBirth>05/05/2001</DateofBirth>
    <Phone>632 869 8779</Phone>
    <Email>nzimmermeister16@barnesandnoble.com</Email>
  </student><student>
    <CNE>990</CNE>
    <LastName>Stidever</LastName>
    <FirstName>Ursola</FirstName>
    <DateofBirth>08/08/1998</DateofBirth>
    <Phone>101 297 2706</Phone>
    <Email>vmcgilleghole17@reverbnation.com</Email>
  </student><student>
    <CNE>991</CNE>
    <LastName>Hammersley</LastName>
    <FirstName>Sumner</FirstName>
    <DateofBirth>16/03/1999</DateofBirth>
    <Phone>659 119 6194</Phone>
    <Email>bmacconnell18@oaic.gov.au</Email>
  </student><student>
    <CNE>992</CNE>
    <LastName>Thornthwaite</LastName>
    <FirstName>Rosalynd</FirstName>
    <DateofBirth>24/09/1999</DateofBirth>
    <Phone>116 449 6113</Phone>
    <Email>fstapforth19@nationalgeographic.com</Email>
  </student><student>
    <CNE>993</CNE>
    <LastName>Quade</LastName>
    <FirstName>Ibby</FirstName>
    <DateofBirth>19/09/2001</DateofBirth>
    <Phone>590 519 5817</Phone>
    <Email>nlittleproud1a@ehow.com</Email>
  </student><student>
    <CNE>994</CNE>
    <LastName>Goodhand</LastName>
    <FirstName>Trumaine</FirstName>
    <DateofBirth>04/10/2001</DateofBirth>
    <Phone>733 294 4074</Phone>
    <Email>njendrassik1b@cnbc.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr3.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>995</CNE>
    <LastName>Cazalet</LastName>
    <FirstName>Agnes</FirstName>
    <DateofBirth>10/08/2001</DateofBirth>
    <Phone>678 951 8008</Phone>
    <Email>eerrigo1c@opera.com</Email>
  </student><student>
    <CNE>996</CNE>
    <LastName>Vest</LastName>
    <FirstName>Rosalinde</FirstName>
    <DateofBirth>10/11/1998</DateofBirth>
    <Phone>836 273 0738</Phone>
    <Email>kburfoot1d@techcrunch.com</Email>
  </student><student>
    <CNE>997</CNE>
    <LastName>Caldecott</LastName>
    <FirstName>Jany</FirstName>
    <DateofBirth>26/04/1998</DateofBirth>
    <Phone>896 557 2035</Phone>
    <Email>rkeher1e@kickstarter.com</Email>
  </student><student>
    <CNE>998</CNE>
    <LastName>Aylesbury</LastName>
    <FirstName>Buck</FirstName>
    <DateofBirth>22/06/2000</DateofBirth>
    <Phone>225 405 4042</Phone>
    <Email>jbretelle1f@moonfruit.com</Email>
  </student><student>
    <CNE>999</CNE>
    <LastName>Dutton</LastName>
    <FirstName>Lauri</FirstName>
    <DateofBirth>26/09/1998</DateofBirth>
    <Phone>631 180 2768</Phone>
    <Email>eproom1g@multiply.com</Email>
  </student><student>
    <CNE>1000</CNE>
    <LastName>Beamand</LastName>
    <FirstName>Odelinda</FirstName>
    <DateofBirth>27/02/2000</DateofBirth>
    <Phone>951 917 9212</Phone>
    <Email>mcrosland1h@theguardian.com</Email>
  </student><student>
    <CNE>1001</CNE>
    <LastName>Larn</LastName>
    <FirstName>Lay</FirstName>
    <DateofBirth>16/07/2001</DateofBirth>
    <Phone>378 488 9012</Phone>
    <Email>vandres1i@google.co.uk</Email>
  </student><student>
    <CNE>1002</CNE>
    <LastName>Snape</LastName>
    <FirstName>Jacki</FirstName>
    <DateofBirth>30/04/1998</DateofBirth>
    <Phone>928 149 0883</Phone>
    <Email>bgeikie1j@biblegateway.com</Email>
  </student><student>
    <CNE>1003</CNE>
    <LastName>Bracchi</LastName>
    <FirstName>Marchall</FirstName>
    <DateofBirth>16/10/2000</DateofBirth>
    <Phone>534 403 6592</Phone>
    <Email>gdalwis1k@tinypic.com</Email>
  </student><student>
    <CNE>1004</CNE>
    <LastName>Skeermor</LastName>
    <FirstName>Waring</FirstName>
    <DateofBirth>25/11/2001</DateofBirth>
    <Phone>339 865 1840</Phone>
    <Email>dmarchment1l@wunderground.com</Email>
  </student><student>
    <CNE>1005</CNE>
    <LastName>Alison</LastName>
    <FirstName>Rana</FirstName>
    <DateofBirth>31/01/1999</DateofBirth>
    <Phone>862 565 2454</Phone>
    <Email>datchly1m@icio.us</Email>
  </student><student>
    <CNE>1006</CNE>
    <LastName>Boggish</LastName>
    <FirstName>Mahalia</FirstName>
    <DateofBirth>24/03/1999</DateofBirth>
    <Phone>547 683 1343</Phone>
    <Email>atiplady1n@blogs.com</Email>
  </student><student>
    <CNE>1007</CNE>
    <LastName>Kumar</LastName>
    <FirstName>Rickie</FirstName>
    <DateofBirth>20/04/2001</DateofBirth>
    <Phone>273 699 0936</Phone>
    <Email>jcowill1o@etsy.com</Email>
  </student><student>
    <CNE>1008</CNE>
    <LastName>Sarch</LastName>
    <FirstName>Faun</FirstName>
    <DateofBirth>14/03/1999</DateofBirth>
    <Phone>110 612 6973</Phone>
    <Email>akidd1p@alibaba.com</Email>
  </student><student>
    <CNE>1009</CNE>
    <LastName>Blewitt</LastName>
    <FirstName>Bridget</FirstName>
    <DateofBirth>10/10/1999</DateofBirth>
    <Phone>325 990 7776</Phone>
    <Email>bbabidge1q@shinystat.com</Email>
  </student><student>
    <CNE>1010</CNE>
    <LastName>Le Friec</LastName>
    <FirstName>Kennith</FirstName>
    <DateofBirth>06/06/2001</DateofBirth>
    <Phone>430 606 3999</Phone>
    <Email>apeppin1r@smh.com.au</Email>
  </student><student>
    <CNE>1011</CNE>
    <LastName>Vasishchev</LastName>
    <FirstName>Avie</FirstName>
    <DateofBirth>10/03/2000</DateofBirth>
    <Phone>895 219 5689</Phone>
    <Email>wcondict1s@tuttocitta.it</Email>
  </student><student>
    <CNE>1012</CNE>
    <LastName>Bandt</LastName>
    <FirstName>Giacobo</FirstName>
    <DateofBirth>13/10/2001</DateofBirth>
    <Phone>271 606 1403</Phone>
    <Email>rbacchus1t@businessweek.com</Email>
  </student><student>
    <CNE>1013</CNE>
    <LastName>Loeber</LastName>
    <FirstName>Lia</FirstName>
    <DateofBirth>24/07/1998</DateofBirth>
    <Phone>654 816 6711</Phone>
    <Email>bspridgen1u@cargocollective.com</Email>
  </student><student>
    <CNE>1014</CNE>
    <LastName>Roisen</LastName>
    <FirstName>Rhys</FirstName>
    <DateofBirth>27/06/2000</DateofBirth>
    <Phone>204 415 2428</Phone>
    <Email>kbeament1v@mit.edu</Email>
  </student><student>
    <CNE>1015</CNE>
    <LastName>Wreath</LastName>
    <FirstName>Alikee</FirstName>
    <DateofBirth>20/02/2001</DateofBirth>
    <Phone>218 790 4099</Phone>
    <Email>cstaterfield1w@usda.gov</Email>
  </student><student>
    <CNE>1016</CNE>
    <LastName>Annice</LastName>
    <FirstName>Tedi</FirstName>
    <DateofBirth>27/04/1999</DateofBirth>
    <Phone>495 284 0442</Phone>
    <Email>ssellars1x@clickbank.net</Email>
  </student><student>
    <CNE>1017</CNE>
    <LastName>Kermitt</LastName>
    <FirstName>Lesya</FirstName>
    <DateofBirth>31/08/1998</DateofBirth>
    <Phone>487 512 8164</Phone>
    <Email>ifeldklein1y@myspace.com</Email>
  </student><student>
    <CNE>1018</CNE>
    <LastName>Canellas</LastName>
    <FirstName>Aldo</FirstName>
    <DateofBirth>16/10/1998</DateofBirth>
    <Phone>716 786 2615</Phone>
    <Email>dfeares1z@wunderground.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_GINF2_Gr3.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>18006869</CNE>
    <LastName>TAALI&#xA0;</LastName>
    <FirstName>HOUDA</FirstName>
    <DateofBirth>3/12/2001</DateofBirth>
    <Phone>684004402</Phone>
    <Email>aliquam@NullafacilisiSed.net</Email>
  </student><student>
    <CNE>18008567</CNE>
    <LastName>ZENAGUI&#xA0;</LastName>
    <FirstName>RABIA</FirstName>
    <DateofBirth>7/24/1997</DateofBirth>
    <Phone>02 34 13 92 94</Phone>
    <Email>aliquim@NullafacilisiSed.net</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr10.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1163</CNE>
    <LastName>Dossetter</LastName>
    <FirstName>Andreas</FirstName>
    <DateofBirth>04/04/2001</DateofBirth>
    <Phone>101 325 1401</Phone>
    <Email>kmarkussen60@surveymonkey.com</Email>
  </student><student>
    <CNE>1164</CNE>
    <LastName>Antrim</LastName>
    <FirstName>Joelie</FirstName>
    <DateofBirth>19/05/1998</DateofBirth>
    <Phone>675 994 1727</Phone>
    <Email>ltommasetti61@sun.com</Email>
  </student><student>
    <CNE>1165</CNE>
    <LastName>Bartoszewski</LastName>
    <FirstName>Jonell</FirstName>
    <DateofBirth>22/07/2000</DateofBirth>
    <Phone>918 282 9632</Phone>
    <Email>dtrustrie62@state.tx.us</Email>
  </student><student>
    <CNE>1166</CNE>
    <LastName>Sailer</LastName>
    <FirstName>Lew</FirstName>
    <DateofBirth>22/11/1998</DateofBirth>
    <Phone>784 588 6513</Phone>
    <Email>apassingham63@baidu.com</Email>
  </student><student>
    <CNE>1167</CNE>
    <LastName>Strode</LastName>
    <FirstName>Brucie</FirstName>
    <DateofBirth>11/04/1999</DateofBirth>
    <Phone>134 788 8730</Phone>
    <Email>ginsoll64@dedecms.com</Email>
  </student><student>
    <CNE>1168</CNE>
    <LastName>Trathen</LastName>
    <FirstName>Sinclare</FirstName>
    <DateofBirth>22/02/1999</DateofBirth>
    <Phone>984 738 5215</Phone>
    <Email>hniven65@nba.com</Email>
  </student><student>
    <CNE>1169</CNE>
    <LastName>Farrens</LastName>
    <FirstName>Emilee</FirstName>
    <DateofBirth>11/01/2001</DateofBirth>
    <Phone>950 782 7981</Phone>
    <Email>mwallentin66@tmall.com</Email>
  </student><student>
    <CNE>1170</CNE>
    <LastName>Pringuer</LastName>
    <FirstName>Pennie</FirstName>
    <DateofBirth>13/08/2001</DateofBirth>
    <Phone>397 264 8208</Phone>
    <Email>aburgane67@java.com</Email>
  </student><student>
    <CNE>1171</CNE>
    <LastName>Hurdwell</LastName>
    <FirstName>Ian</FirstName>
    <DateofBirth>04/11/2001</DateofBirth>
    <Phone>299 788 4368</Phone>
    <Email>cstangel68@cisco.com</Email>
  </student><student>
    <CNE>1172</CNE>
    <LastName>Welton</LastName>
    <FirstName>Gray</FirstName>
    <DateofBirth>03/09/2000</DateofBirth>
    <Phone>655 678 1089</Phone>
    <Email>clinfoot69@hp.com</Email>
  </student><student>
    <CNE>1173</CNE>
    <LastName>Greest</LastName>
    <FirstName>Adelaide</FirstName>
    <DateofBirth>02/06/1999</DateofBirth>
    <Phone>669 456 4813</Phone>
    <Email>jeaglesham6a@prlog.org</Email>
  </student><student>
    <CNE>1174</CNE>
    <LastName>Grichukhanov</LastName>
    <FirstName>Beilul</FirstName>
    <DateofBirth>25/11/2001</DateofBirth>
    <Phone>845 233 8438</Phone>
    <Email>jlucus6b@berkeley.edu</Email>
  </student><student>
    <CNE>1175</CNE>
    <LastName>Sumption</LastName>
    <FirstName>Marten</FirstName>
    <DateofBirth>13/08/2001</DateofBirth>
    <Phone>602 991 9470</Phone>
    <Email>jlacaze6c@ed.gov</Email>
  </student><student>
    <CNE>1176</CNE>
    <LastName>Lewsey</LastName>
    <FirstName>Colly</FirstName>
    <DateofBirth>03/10/2000</DateofBirth>
    <Phone>520 485 9031</Phone>
    <Email>mguidone6d@wufoo.com</Email>
  </student><student>
    <CNE>1177</CNE>
    <LastName>Gromley</LastName>
    <FirstName>Fabio</FirstName>
    <DateofBirth>12/08/1998</DateofBirth>
    <Phone>216 811 7447</Phone>
    <Email>emacskeaghan6e@behance.net</Email>
  </student><student>
    <CNE>1178</CNE>
    <LastName>Pittham</LastName>
    <FirstName>Pauletta</FirstName>
    <DateofBirth>22/08/1999</DateofBirth>
    <Phone>950 747 2399</Phone>
    <Email>rchevins6f@ed.gov</Email>
  </student><student>
    <CNE>1179</CNE>
    <LastName>McIsaac</LastName>
    <FirstName>Dorothy</FirstName>
    <DateofBirth>15/07/2001</DateofBirth>
    <Phone>351 706 2150</Phone>
    <Email>rkelleher6g@e-recht24.de</Email>
  </student><student>
    <CNE>1180</CNE>
    <LastName>Bath</LastName>
    <FirstName>Becky</FirstName>
    <DateofBirth>27/10/2001</DateofBirth>
    <Phone>274 100 6766</Phone>
    <Email>ntruwert6h@mashable.com</Email>
  </student><student>
    <CNE>1181</CNE>
    <LastName>Leckenby</LastName>
    <FirstName>Dukey</FirstName>
    <DateofBirth>28/12/2000</DateofBirth>
    <Phone>475 584 6882</Phone>
    <Email>bsalzen6i@cbsnews.com</Email>
  </student><student>
    <CNE>1182</CNE>
    <LastName>Piotrowski</LastName>
    <FirstName>Heda</FirstName>
    <DateofBirth>09/07/1999</DateofBirth>
    <Phone>744 825 0396</Phone>
    <Email>jarp6j@fastcompany.com</Email>
  </student><student>
    <CNE>1183</CNE>
    <LastName>Ciobotaru</LastName>
    <FirstName>Marga</FirstName>
    <DateofBirth>16/04/1999</DateofBirth>
    <Phone>353 791 8250</Phone>
    <Email>ccowap6k@cbsnews.com</Email>
  </student><student>
    <CNE>1184</CNE>
    <LastName>Parsonage</LastName>
    <FirstName>Luciano</FirstName>
    <DateofBirth>27/03/1998</DateofBirth>
    <Phone>856 495 8732</Phone>
    <Email>bfawcett6l@hc360.com</Email>
  </student><student>
    <CNE>1185</CNE>
    <LastName>Lorenc</LastName>
    <FirstName>Terrance</FirstName>
    <DateofBirth>28/10/2001</DateofBirth>
    <Phone>304 189 3503</Phone>
    <Email>wspaduzza6m@state.gov</Email>
  </student><student>
    <CNE>1186</CNE>
    <LastName>Hargate</LastName>
    <FirstName>Drake</FirstName>
    <DateofBirth>17/11/1999</DateofBirth>
    <Phone>402 311 6992</Phone>
    <Email>benglish6n@netvibes.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr7.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1091</CNE>
    <LastName>Motten</LastName>
    <FirstName>Bevin</FirstName>
    <DateofBirth>05/01/2001</DateofBirth>
    <Phone>462 512 1942</Phone>
    <Email>rwalkling40@indiegogo.com</Email>
  </student><student>
    <CNE>1092</CNE>
    <LastName>Dymond</LastName>
    <FirstName>Temp</FirstName>
    <DateofBirth>23/07/1999</DateofBirth>
    <Phone>690 179 2316</Phone>
    <Email>mryley41@vimeo.com</Email>
  </student><student>
    <CNE>1093</CNE>
    <LastName>De Beauchemp</LastName>
    <FirstName>Bethena</FirstName>
    <DateofBirth>21/02/1999</DateofBirth>
    <Phone>344 453 3278</Phone>
    <Email>dbenzies42@miibeian.gov.cn</Email>
  </student><student>
    <CNE>1094</CNE>
    <LastName>Stempe</LastName>
    <FirstName>Thedric</FirstName>
    <DateofBirth>22/01/2000</DateofBirth>
    <Phone>368 323 6456</Phone>
    <Email>nrenachowski43@buzzfeed.com</Email>
  </student><student>
    <CNE>1095</CNE>
    <LastName>Labone</LastName>
    <FirstName>Bunnie</FirstName>
    <DateofBirth>23/04/1999</DateofBirth>
    <Phone>169 406 3769</Phone>
    <Email>hrickell44@hibu.com</Email>
  </student><student>
    <CNE>1096</CNE>
    <LastName>Thirst</LastName>
    <FirstName>Mallorie</FirstName>
    <DateofBirth>01/10/2000</DateofBirth>
    <Phone>564 297 3303</Phone>
    <Email>dwyndham45@pagesperso-orange.fr</Email>
  </student><student>
    <CNE>1097</CNE>
    <LastName>Geraldez</LastName>
    <FirstName>Sebastian</FirstName>
    <DateofBirth>12/04/1998</DateofBirth>
    <Phone>815 202 6071</Phone>
    <Email>fscotti46@latimes.com</Email>
  </student><student>
    <CNE>1098</CNE>
    <LastName>Rivitt</LastName>
    <FirstName>Clotilda</FirstName>
    <DateofBirth>10/01/1998</DateofBirth>
    <Phone>316 461 9156</Phone>
    <Email>kpowlett47@cpanel.net</Email>
  </student><student>
    <CNE>1099</CNE>
    <LastName>Malthouse</LastName>
    <FirstName>Odelinda</FirstName>
    <DateofBirth>26/03/2000</DateofBirth>
    <Phone>105 524 0026</Phone>
    <Email>mkuhle48@mediafire.com</Email>
  </student><student>
    <CNE>1100</CNE>
    <LastName>Pottell</LastName>
    <FirstName>Bernadene</FirstName>
    <DateofBirth>06/08/1998</DateofBirth>
    <Phone>122 802 6134</Phone>
    <Email>blucia49@cnn.com</Email>
  </student><student>
    <CNE>1101</CNE>
    <LastName>Sackes</LastName>
    <FirstName>Garv</FirstName>
    <DateofBirth>08/05/1998</DateofBirth>
    <Phone>294 405 1757</Phone>
    <Email>mdaniells4a@fema.gov</Email>
  </student><student>
    <CNE>1102</CNE>
    <LastName>Genny</LastName>
    <FirstName>Rhoda</FirstName>
    <DateofBirth>28/03/1998</DateofBirth>
    <Phone>973 369 3482</Phone>
    <Email>btejero4b@spiegel.de</Email>
  </student><student>
    <CNE>1103</CNE>
    <LastName>Perrott</LastName>
    <FirstName>Gavrielle</FirstName>
    <DateofBirth>01/07/1998</DateofBirth>
    <Phone>491 947 6752</Phone>
    <Email>hmcleod4c@yahoo.com</Email>
  </student><student>
    <CNE>1104</CNE>
    <LastName>Parkinson</LastName>
    <FirstName>Danyette</FirstName>
    <DateofBirth>24/11/2001</DateofBirth>
    <Phone>900 883 2906</Phone>
    <Email>hmariolle4d@fc2.com</Email>
  </student><student>
    <CNE>1105</CNE>
    <LastName>Denyakin</LastName>
    <FirstName>Even</FirstName>
    <DateofBirth>24/10/1999</DateofBirth>
    <Phone>345 162 9490</Phone>
    <Email>nbessett4e@illinois.edu</Email>
  </student><student>
    <CNE>1106</CNE>
    <LastName>Stedson</LastName>
    <FirstName>Catharine</FirstName>
    <DateofBirth>31/10/1999</DateofBirth>
    <Phone>143 204 6967</Phone>
    <Email>jgyves4f@springer.com</Email>
  </student><student>
    <CNE>1107</CNE>
    <LastName>Blaine</LastName>
    <FirstName>Lotta</FirstName>
    <DateofBirth>15/09/2001</DateofBirth>
    <Phone>803 347 2907</Phone>
    <Email>ajaime4g@creativecommons.org</Email>
  </student><student>
    <CNE>1108</CNE>
    <LastName>Crebbin</LastName>
    <FirstName>Anet</FirstName>
    <DateofBirth>25/09/1999</DateofBirth>
    <Phone>160 966 0628</Phone>
    <Email>bbrimfield4h@google.nl</Email>
  </student><student>
    <CNE>1109</CNE>
    <LastName>O' Timony</LastName>
    <FirstName>Ermengarde</FirstName>
    <DateofBirth>30/06/1999</DateofBirth>
    <Phone>884 795 3934</Phone>
    <Email>eesland4i@chron.com</Email>
  </student><student>
    <CNE>1110</CNE>
    <LastName>Prott</LastName>
    <FirstName>Sly</FirstName>
    <DateofBirth>05/05/2000</DateofBirth>
    <Phone>341 987 4492</Phone>
    <Email>cmephan4j@yolasite.com</Email>
  </student><student>
    <CNE>1111</CNE>
    <LastName>Buyers</LastName>
    <FirstName>Colet</FirstName>
    <DateofBirth>18/08/2001</DateofBirth>
    <Phone>697 387 8242</Phone>
    <Email>cwesson4k@domainmarket.com</Email>
  </student><student>
    <CNE>1112</CNE>
    <LastName>Jeandillou</LastName>
    <FirstName>Herold</FirstName>
    <DateofBirth>04/04/1999</DateofBirth>
    <Phone>866 881 7119</Phone>
    <Email>bdounbare4l@yellowbook.com</Email>
  </student><student>
    <CNE>1113</CNE>
    <LastName>Eustice</LastName>
    <FirstName>Tallie</FirstName>
    <DateofBirth>08/02/2000</DateofBirth>
    <Phone>869 210 2628</Phone>
    <Email>mjessard4m@unblog.fr</Email>
  </student><student>
    <CNE>1114</CNE>
    <LastName>Balden</LastName>
    <FirstName>Hilary</FirstName>
    <DateofBirth>09/08/2000</DateofBirth>
    <Phone>572 133 0965</Phone>
    <Email>lwetherald4n@taobao.com</Email>
  </student></students>
