=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersDeValidation/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
elementFormDefault="qualified">

<xs:element name="students">
   <xs:complexType>
     <xs:sequence>
      <xs:element name="student" maxOccurs="240" minOccurs="48">
       <xs:complexType>
        <xs:sequence>
          <xs:element name="CNE" type="xs:string"/>
          <xs:element name="LastName" type="xs:string"/>
          <xs:element name="FirstName" type="xs:string"/>
          <xs:element name="DateofBirth" type="xs:date"/>
          <xs:element name="Phone" type="xs:string"/>
          <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType> 
  </xs:element>

  </xs:schema>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP2_Gr5.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>803</CNE>
    <LastName>McCluin</LastName>
    <FirstName>Randie</FirstName>
    <DateofBirth>17/10/1999</DateofBirth>
    <Phone>786 900 2696</Phone>
    <Email>fplan2o@sfgate.com</Email>
  </student><student>
    <CNE>804</CNE>
    <LastName>Enrigo</LastName>
    <FirstName>Connie</FirstName>
    <DateofBirth>06/05/1998</DateofBirth>
    <Phone>755 174 4344</Phone>
    <Email>mfaulks2p@dropbox.com</Email>
  </student><student>
    <CNE>805</CNE>
    <LastName>Lett</LastName>
    <FirstName>Orin</FirstName>
    <DateofBirth>18/01/1999</DateofBirth>
    <Phone>942 835 1203</Phone>
    <Email>hprugel2q@desdev.cn</Email>
  </student><student>
    <CNE>806</CNE>
    <LastName>Slograve</LastName>
    <FirstName>Kim</FirstName>
    <DateofBirth>28/09/1998</DateofBirth>
    <Phone>765 790 8916</Phone>
    <Email>scowpland2r@whitehouse.gov</Email>
  </student><student>
    <CNE>807</CNE>
    <LastName>Burchett</LastName>
    <FirstName>Vannie</FirstName>
    <DateofBirth>27/08/1999</DateofBirth>
    <Phone>216 173 4620</Phone>
    <Email>badran2s@usda.gov</Email>
  </student><student>
    <CNE>808</CNE>
    <LastName>Prudence</LastName>
    <FirstName>Vally</FirstName>
    <DateofBirth>27/02/1999</DateofBirth>
    <Phone>754 892 4412</Phone>
    <Email>aruseworth2t@alibaba.com</Email>
  </student><student>
    <CNE>809</CNE>
    <LastName>Moraleda</LastName>
    <FirstName>Lin</FirstName>
    <DateofBirth>30/03/2000</DateofBirth>
    <Phone>634 984 6838</Phone>
    <Email>sgahan2u@home.pl</Email>
  </student><student>
    <CNE>810</CNE>
    <LastName>Wellfare</LastName>
    <FirstName>Coraline</FirstName>
    <DateofBirth>28/02/1998</DateofBirth>
    <Phone>516 249 8281</Phone>
    <Email>jbraganza2v@typepad.com</Email>
  </student><student>
    <CNE>811</CNE>
    <LastName>Lanaway</LastName>
    <FirstName>Robbie</FirstName>
    <DateofBirth>12/01/1999</DateofBirth>
    <Phone>940 467 8436</Phone>
    <Email>lcamble2w@wunderground.com</Email>
  </student><student>
    <CNE>812</CNE>
    <LastName>Riddoch</LastName>
    <FirstName>Timotheus</FirstName>
    <DateofBirth>22/02/1999</DateofBirth>
    <Phone>303 700 0259</Phone>
    <Email>zkrishtopaittis2x@reuters.com</Email>
  </student><student>
    <CNE>813</CNE>
    <LastName>Reynard</LastName>
    <FirstName>Ally</FirstName>
    <DateofBirth>29/07/1999</DateofBirth>
    <Phone>609 300 7933</Phone>
    <Email>mhofer2y@arizona.edu</Email>
  </student><student>
    <CNE>814</CNE>
    <LastName>Parzis</LastName>
    <FirstName>Betteann</FirstName>
    <DateofBirth>09/08/1998</DateofBirth>
    <Phone>927 264 4231</Phone>
    <Email>telcombe2z@senate.gov</Email>
  </student><student>
    <CNE>815</CNE>
    <LastName>Felgate</LastName>
    <FirstName>Isidora</FirstName>
    <DateofBirth>19/07/1998</DateofBirth>
    <Phone>787 952 8599</Phone>
    <Email>dparzis30@free.fr</Email>
  </student><student>
    <CNE>816</CNE>
    <LastName>Cardenas</LastName>
    <FirstName>Connie</FirstName>
    <DateofBirth>04/03/2000</DateofBirth>
    <Phone>271 974 7209</Phone>
    <Email>ddyet31@163.com</Email>
  </student><student>
    <CNE>817</CNE>
    <LastName>Layhe</LastName>
    <FirstName>Vannie</FirstName>
    <DateofBirth>27/09/1998</DateofBirth>
    <Phone>986 885 3603</Phone>
    <Email>apetters32@businessinsider.com</Email>
  </student><student>
    <CNE>818</CNE>
    <LastName>Stevenson</LastName>
    <FirstName>Sofia</FirstName>
    <DateofBirth>31/10/1999</DateofBirth>
    <Phone>591 591 1262</Phone>
    <Email>nmurrell33@de.vu</Email>
  </student><student>
    <CNE>819</CNE>
    <LastName>Chaise</LastName>
    <FirstName>Joelly</FirstName>
    <DateofBirth>12/01/1999</DateofBirth>
    <Phone>623 763 4822</Phone>
    <Email>vstclair34@google.nl</Email>
  </student><student>
    <CNE>820</CNE>
    <LastName>Myott</LastName>
    <FirstName>Basia</FirstName>
    <DateofBirth>03/04/1998</DateofBirth>
    <Phone>168 730 0592</Phone>
    <Email>eelizabeth35@uiuc.edu</Email>
  </student><student>
    <CNE>821</CNE>
    <LastName>Baise</LastName>
    <FirstName>Michaelina</FirstName>
    <DateofBirth>22/01/1998</DateofBirth>
    <Phone>394 868 7358</Phone>
    <Email>cspragge36@nydailynews.com</Email>
  </student><student>
    <CNE>822</CNE>
    <LastName>Gledhall</LastName>
    <FirstName>Ritchie</FirstName>
    <DateofBirth>08/02/1998</DateofBirth>
    <Phone>183 366 3594</Phone>
    <Email>dstutter37@amazon.co.jp</Email>
  </student><student>
    <CNE>823</CNE>
    <LastName>Allbon</LastName>
    <FirstName>Bertina</FirstName>
    <DateofBirth>14/10/1998</DateofBirth>
    <Phone>143 618 4947</Phone>
    <Email>elakeland38@shinystat.com</Email>
  </student><student>
    <CNE>824</CNE>
    <LastName>Silkston</LastName>
    <FirstName>Genevra</FirstName>
    <DateofBirth>24/11/1998</DateofBirth>
    <Phone>737 659 4812</Phone>
    <Email>felstub39@blogtalkradio.com</Email>
  </student><student>
    <CNE>825</CNE>
    <LastName>Grierson</LastName>
    <FirstName>Bobby</FirstName>
    <DateofBirth>31/10/1998</DateofBirth>
    <Phone>696 182 8415</Phone>
    <Email>fkerslake3a@facebook.com</Email>
  </student><student>
    <CNE>826</CNE>
    <LastName>MacKeever</LastName>
    <FirstName>Willie</FirstName>
    <DateofBirth>11/05/2000</DateofBirth>
    <Phone>171 228 6492</Phone>
    <Email>jchasmer3b@cyberchimps.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr1.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>947</CNE>
    <LastName>Kindell</LastName>
    <FirstName>Bevon</FirstName>
    <DateofBirth>18/03/2001</DateofBirth>
    <Phone>895 874 1362</Phone>
    <Email>kgratton0@comsenz.com</Email>
  </student><student>
    <CNE>948</CNE>
    <LastName>Durak</LastName>
    <FirstName>Lottie</FirstName>
    <DateofBirth>07/12/1999</DateofBirth>
    <Phone>274 958 7127</Phone>
    <Email>mfeavers1@yahoo.com</Email>
  </student><student>
    <CNE>949</CNE>
    <LastName>Treven</LastName>
    <FirstName>L;urette</FirstName>
    <DateofBirth>16/05/1999</DateofBirth>
    <Phone>737 407 3617</Phone>
    <Email>doiseau2@com.com</Email>
  </student><student>
    <CNE>950</CNE>
    <LastName>Paulig</LastName>
    <FirstName>Selene</FirstName>
    <DateofBirth>11/03/2001</DateofBirth>
    <Phone>449 122 3376</Phone>
    <Email>hquaif3@vk.com</Email>
  </student><student>
    <CNE>951</CNE>
    <LastName>Reddie</LastName>
    <FirstName>Beck</FirstName>
    <DateofBirth>12/02/2000</DateofBirth>
    <Phone>880 122 3441</Phone>
    <Email>hvaskov4@smugmug.com</Email>
  </student><student>
    <CNE>952</CNE>
    <LastName>Bingall</LastName>
    <FirstName>Halie</FirstName>
    <DateofBirth>07/10/2001</DateofBirth>
    <Phone>757 705 7394</Phone>
    <Email>ahartnup5@time.com</Email>
  </student><student>
    <CNE>953</CNE>
    <LastName>Lillee</LastName>
    <FirstName>Jasmin</FirstName>
    <DateofBirth>21/04/1998</DateofBirth>
    <Phone>810 218 8096</Phone>
    <Email>fdornin6@mtv.com</Email>
  </student><student>
    <CNE>954</CNE>
    <LastName>Armstrong</LastName>
    <FirstName>Corine</FirstName>
    <DateofBirth>12/08/2000</DateofBirth>
    <Phone>247 307 0312</Phone>
    <Email>adeftie7@nba.com</Email>
  </student><student>
    <CNE>955</CNE>
    <LastName>Ugolini</LastName>
    <FirstName>Currie</FirstName>
    <DateofBirth>27/12/1999</DateofBirth>
    <Phone>879 267 7263</Phone>
    <Email>fdavet8@fda.gov</Email>
  </student><student>
    <CNE>956</CNE>
    <LastName>Hallad</LastName>
    <FirstName>Barbe</FirstName>
    <DateofBirth>24/05/1998</DateofBirth>
    <Phone>928 497 2546</Phone>
    <Email>rkinson9@youtube.com</Email>
  </student><student>
    <CNE>957</CNE>
    <LastName>Sperring</LastName>
    <FirstName>Glynis</FirstName>
    <DateofBirth>16/12/1998</DateofBirth>
    <Phone>972 473 9366</Phone>
    <Email>ynorthidgea@joomla.org</Email>
  </student><student>
    <CNE>958</CNE>
    <LastName>Staresmeare</LastName>
    <FirstName>Hubie</FirstName>
    <DateofBirth>25/05/1998</DateofBirth>
    <Phone>278 277 9521</Phone>
    <Email>bhabgoodb@cdbaby.com</Email>
  </student><student>
    <CNE>959</CNE>
    <LastName>O'Regan</LastName>
    <FirstName>Saudra</FirstName>
    <DateofBirth>04/08/2000</DateofBirth>
    <Phone>944 652 9437</Phone>
    <Email>kheggisonc@bloglines.com</Email>
  </student><student>
    <CNE>960</CNE>
    <LastName>Paggitt</LastName>
    <FirstName>Desi</FirstName>
    <DateofBirth>03/12/2001</DateofBirth>
    <Phone>140 278 5207</Phone>
    <Email>aproffittd@zimbio.com</Email>
  </student><student>
    <CNE>961</CNE>
    <LastName>Pellman</LastName>
    <FirstName>Verna</FirstName>
    <DateofBirth>28/06/2001</DateofBirth>
    <Phone>141 526 4956</Phone>
    <Email>asigarse@about.me</Email>
  </student><student>
    <CNE>962</CNE>
    <LastName>Kildahl</LastName>
    <FirstName>Shirlene</FirstName>
    <DateofBirth>08/04/1998</DateofBirth>
    <Phone>293 712 7875</Phone>
    <Email>lburtonwoodf@upenn.edu</Email>
  </student><student>
    <CNE>963</CNE>
    <LastName>Fetherston</LastName>
    <FirstName>Krisha</FirstName>
    <DateofBirth>26/10/2001</DateofBirth>
    <Phone>508 188 8449</Phone>
    <Email>gschiellg@typepad.com</Email>
  </student><student>
    <CNE>964</CNE>
    <LastName>Treanor</LastName>
    <FirstName>Gerty</FirstName>
    <DateofBirth>01/02/2000</DateofBirth>
    <Phone>845 592 5119</Phone>
    <Email>kweedsh@ow.ly</Email>
  </student><student>
    <CNE>965</CNE>
    <LastName>Schirak</LastName>
    <FirstName>Charles</FirstName>
    <DateofBirth>19/02/1999</DateofBirth>
    <Phone>419 336 6937</Phone>
    <Email>fmidsoni@weather.com</Email>
  </student><student>
    <CNE>966</CNE>
    <LastName>Alelsandrovich</LastName>
    <FirstName>Katuscha</FirstName>
    <DateofBirth>25/02/1998</DateofBirth>
    <Phone>303 220 5285</Phone>
    <Email>iivanikhinj@hhs.gov</Email>
  </student><student>
    <CNE>967</CNE>
    <LastName>Arrol</LastName>
    <FirstName>Charissa</FirstName>
    <DateofBirth>28/04/1998</DateofBirth>
    <Phone>184 741 2562</Phone>
    <Email>htevelovk@thetimes.co.uk</Email>
  </student><student>
    <CNE>968</CNE>
    <LastName>Graben</LastName>
    <FirstName>Merrielle</FirstName>
    <DateofBirth>03/10/1998</DateofBirth>
    <Phone>689 331 2520</Phone>
    <Email>dmactimpanyl@rakuten.co.jp</Email>
  </student><student>
    <CNE>969</CNE>
    <LastName>Mercik</LastName>
    <FirstName>Lucy</FirstName>
    <DateofBirth>17/03/1999</DateofBirth>
    <Phone>977 587 4639</Phone>
    <Email>gmollisonm@amazon.de</Email>
  </student><student>
    <CNE>970</CNE>
    <LastName>Taft</LastName>
    <FirstName>Evita</FirstName>
    <DateofBirth>04/11/2000</DateofBirth>
    <Phone>847 310 0536</Phone>
    <Email>cblundenn@paypal.com</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr6.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1067</CNE>
    <LastName>Greenough</LastName>
    <FirstName>Brigitta</FirstName>
    <DateofBirth>07/02/1998</DateofBirth>
    <Phone>423 387 9575</Phone>
    <Email>pboschmann3c@stumbleupon.com</Email>
  </student><student>
    <CNE>1068</CNE>
    <LastName>Dormand</LastName>
    <FirstName>Des</FirstName>
    <DateofBirth>16/07/2000</DateofBirth>
    <Phone>725 662 7907</Phone>
    <Email>clidierth3d@chron.com</Email>
  </student><student>
    <CNE>1069</CNE>
    <LastName>Jockle</LastName>
    <FirstName>Earvin</FirstName>
    <DateofBirth>23/06/1998</DateofBirth>
    <Phone>183 413 5449</Phone>
    <Email>jglasard3e@cnn.com</Email>
  </student><student>
    <CNE>1070</CNE>
    <LastName>Slixby</LastName>
    <FirstName>Kathlin</FirstName>
    <DateofBirth>07/12/2000</DateofBirth>
    <Phone>195 723 8886</Phone>
    <Email>lpringell3f@addtoany.com</Email>
  </student><student>
    <CNE>1071</CNE>
    <LastName>Rossiter</LastName>
    <FirstName>Mady</FirstName>
    <DateofBirth>19/02/1998</DateofBirth>
    <Phone>258 451 0075</Phone>
    <Email>pteaser3g@jalbum.net</Email>
  </student><student>
    <CNE>1072</CNE>
    <LastName>Sessuns</LastName>
    <FirstName>Jodee</FirstName>
    <DateofBirth>18/10/2001</DateofBirth>
    <Phone>655 451 1641</Phone>
    <Email>csmart3h@microsoft.com</Email>
  </student><student>
    <CNE>1073</CNE>
    <LastName>Matonin</LastName>
    <FirstName>Devin</FirstName>
    <DateofBirth>08/03/2000</DateofBirth>
    <Phone>343 537 6748</Phone>
    <Email>bjakov3i@dagondesign.com</Email>
  </student><student>
    <CNE>1074</CNE>
    <LastName>Ward</LastName>
    <FirstName>Barbey</FirstName>
    <DateofBirth>07/05/2000</DateofBirth>
    <Phone>521 126 3137</Phone>
    <Email>cblazic3j@ow.ly</Email>
  </student><student>
    <CNE>1075</CNE>
    <LastName>Robinet</LastName>
    <FirstName>Curtis</FirstName>
    <DateofBirth>08/01/1999</DateofBirth>
    <Phone>848 450 5982</Phone>
    <Email>asambells3k@cloudflare.com</Email>
  </student><student>
    <CNE>1076</CNE>
    <LastName>Stearn</LastName>
    <FirstName>Eadie</FirstName>
    <DateofBirth>13/02/1998</DateofBirth>
    <Phone>407 502 6960</Phone>
    <Email>noertzen3l@opera.com</Email>
  </student><student>
    <CNE>1077</CNE>
    <LastName>Pochet</LastName>
    <FirstName>Brianna</FirstName>
    <DateofBirth>28/04/2001</DateofBirth>
    <Phone>786 272 9211</Phone>
    <Email>osyddie3m@pagesperso-orange.fr</Email>
  </student><student>
    <CNE>1078</CNE>
    <LastName>Duiguid</LastName>
    <FirstName>Joyous</FirstName>
    <DateofBirth>06/02/1998</DateofBirth>
    <Phone>974 853 5607</Phone>
    <Email>wcoleby3n@domainmarket.com</Email>
  </student><student>
    <CNE>1079</CNE>
    <LastName>Badgers</LastName>
    <FirstName>Euphemia</FirstName>
    <DateofBirth>01/08/1999</DateofBirth>
    <Phone>184 816 8774</Phone>
    <Email>himason3o@amazon.co.jp</Email>
  </student><student>
    <CNE>1080</CNE>
    <LastName>Gaspar</LastName>
    <FirstName>Ab</FirstName>
    <DateofBirth>15/08/2001</DateofBirth>
    <Phone>571 546 5353</Phone>
    <Email>zbroseke3p@devhub.com</Email>
  </student><student>
    <CNE>1081</CNE>
    <LastName>Milland</LastName>
    <FirstName>Kristina</FirstName>
    <DateofBirth>01/03/1998</DateofBirth>
    <Phone>840 202 0909</Phone>
    <Email>cwhaplington3q@woothemes.com</Email>
  </student><student>
    <CNE>1082</CNE>
    <LastName>Clift</LastName>
    <FirstName>Gaby</FirstName>
    <DateofBirth>09/04/1999</DateofBirth>
    <Phone>881 566 6527</Phone>
    <Email>rconkie3r@aol.com</Email>
  </student><student>
    <CNE>1083</CNE>
    <LastName>McCreath</LastName>
    <FirstName>Selby</FirstName>
    <DateofBirth>03/01/1998</DateofBirth>
    <Phone>416 600 3607</Phone>
    <Email>msevior3s@princeton.edu</Email>
  </student><student>
    <CNE>1084</CNE>
    <LastName>Hatherley</LastName>
    <FirstName>Celestyn</FirstName>
    <DateofBirth>10/06/1999</DateofBirth>
    <Phone>942 494 3662</Phone>
    <Email>cmatveichev3t@dagondesign.com</Email>
  </student><student>
    <CNE>1085</CNE>
    <LastName>Lyffe</LastName>
    <FirstName>Imogene</FirstName>
    <DateofBirth>25/10/2000</DateofBirth>
    <Phone>342 316 8466</Phone>
    <Email>nhovy3u@livejournal.com</Email>
  </student><student>
    <CNE>1086</CNE>
    <LastName>Filan</LastName>
    <FirstName>Marci</FirstName>
    <DateofBirth>04/06/2001</DateofBirth>
    <Phone>874 285 1952</Phone>
    <Email>dsuttling3v@omniture.com</Email>
  </student><student>
    <CNE>1087</CNE>
    <LastName>Hun</LastName>
    <FirstName>Michail</FirstName>
    <DateofBirth>22/08/2001</DateofBirth>
    <Phone>112 335 1991</Phone>
    <Email>hblacklawe3w@imdb.com</Email>
  </student><student>
    <CNE>1088</CNE>
    <LastName>Meritt</LastName>
    <FirstName>Daphene</FirstName>
    <DateofBirth>28/10/1998</DateofBirth>
    <Phone>808 149 7234</Phone>
    <Email>otrinke3x@java.com</Email>
  </student><student>
    <CNE>1089</CNE>
    <LastName>Marcinkowski</LastName>
    <FirstName>Pierrette</FirstName>
    <DateofBirth>08/02/2001</DateofBirth>
    <Phone>305 587 9398</Phone>
    <Email>hcarletti3y@springer.com</Email>
  </student><student>
    <CNE>1090</CNE>
    <LastName>Wooding</LastName>
    <FirstName>Mandi</FirstName>
    <DateofBirth>02/02/2001</DateofBirth>
    <Phone>868 103 9679</Phone>
    <Email>claidel3z@imageshack.us</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP2_Gr10.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>923</CNE>
    <LastName>Rosellini</LastName>
    <FirstName>Tootsie</FirstName>
    <DateofBirth>18/01/1998</DateofBirth>
    <Phone>765 759 5864</Phone>
    <Email>omackstead60@bloglines.com</Email>
  </student><student>
    <CNE>924</CNE>
    <LastName>Sneesbie</LastName>
    <FirstName>Charmain</FirstName>
    <DateofBirth>15/11/1998</DateofBirth>
    <Phone>936 446 8664</Phone>
    <Email>bcrosskell61@sciencedaily.com</Email>
  </student><student>
    <CNE>925</CNE>
    <LastName>Gerwood</LastName>
    <FirstName>Rhona</FirstName>
    <DateofBirth>15/03/2000</DateofBirth>
    <Phone>350 878 0089</Phone>
    <Email>mburkman62@biglobe.ne.jp</Email>
  </student><student>
    <CNE>926</CNE>
    <LastName>Ebbins</LastName>
    <FirstName>Hymie</FirstName>
    <DateofBirth>03/11/2000</DateofBirth>
    <Phone>908 280 2941</Phone>
    <Email>hchurchlow63@wunderground.com</Email>
  </student><student>
    <CNE>927</CNE>
    <LastName>Dunsire</LastName>
    <FirstName>Vivien</FirstName>
    <DateofBirth>21/03/2000</DateofBirth>
    <Phone>661 136 0784</Phone>
    <Email>jratcliff64@scribd.com</Email>
  </student><student>
    <CNE>928</CNE>
    <LastName>Bleackly</LastName>
    <FirstName>Chicky</FirstName>
    <DateofBirth>02/07/1999</DateofBirth>
    <Phone>830 643 6401</Phone>
    <Email>gpogosian65@cocolog-nifty.com</Email>
  </student><student>
    <CNE>929</CNE>
    <LastName>Gerram</LastName>
    <FirstName>Roberta</FirstName>
    <DateofBirth>22/08/1999</DateofBirth>
    <Phone>999 213 7732</Phone>
    <Email>nemps66@booking.com</Email>
  </student><student>
    <CNE>930</CNE>
    <LastName>Speak</LastName>
    <FirstName>Saundra</FirstName>
    <DateofBirth>02/08/2000</DateofBirth>
    <Phone>490 367 5571</Phone>
    <Email>owhatham67@indiatimes.com</Email>
  </student><student>
    <CNE>931</CNE>
    <LastName>Zuan</LastName>
    <FirstName>Alikee</FirstName>
    <DateofBirth>10/02/2000</DateofBirth>
    <Phone>571 166 5876</Phone>
    <Email>eearl68@alexa.com</Email>
  </student><student>
    <CNE>932</CNE>
    <LastName>Blenkhorn</LastName>
    <FirstName>Aluino</FirstName>
    <DateofBirth>15/03/1998</DateofBirth>
    <Phone>316 727 8792</Phone>
    <Email>jburgiss69@ed.gov</Email>
  </student><student>
    <CNE>933</CNE>
    <LastName>Eplett</LastName>
    <FirstName>Stanfield</FirstName>
    <DateofBirth>21/09/1998</DateofBirth>
    <Phone>659 731 1313</Phone>
    <Email>tballing6a@themeforest.net</Email>
  </student><student>
    <CNE>934</CNE>
    <LastName>Phippard</LastName>
    <FirstName>Calida</FirstName>
    <DateofBirth>31/05/1998</DateofBirth>
    <Phone>571 327 1832</Phone>
    <Email>vgallacher6b@sbwire.com</Email>
  </student><student>
    <CNE>935</CNE>
    <LastName>Kubik</LastName>
    <FirstName>Kerrin</FirstName>
    <DateofBirth>05/05/1998</DateofBirth>
    <Phone>709 591 4567</Phone>
    <Email>fegan6c@drupal.org</Email>
  </student><student>
    <CNE>936</CNE>
    <LastName>Gandrich</LastName>
    <FirstName>Cris</FirstName>
    <DateofBirth>17/12/1999</DateofBirth>
    <Phone>720 570 1974</Phone>
    <Email>amatthews6d@sciencedirect.com</Email>
  </student><student>
    <CNE>937</CNE>
    <LastName>Pullin</LastName>
    <FirstName>Gil</FirstName>
    <DateofBirth>28/02/1998</DateofBirth>
    <Phone>664 968 8769</Phone>
    <Email>mirwin6e@acquirethisname.com</Email>
  </student><student>
    <CNE>938</CNE>
    <LastName>Balasin</LastName>
    <FirstName>Berk</FirstName>
    <DateofBirth>04/06/1998</DateofBirth>
    <Phone>865 488 2576</Phone>
    <Email>yormshaw6f@domainmarket.com</Email>
  </student><student>
    <CNE>939</CNE>
    <LastName>Wabersinke</LastName>
    <FirstName>Em</FirstName>
    <DateofBirth>13/07/1999</DateofBirth>
    <Phone>878 864 4955</Phone>
    <Email>rmacvaugh6g@unc.edu</Email>
  </student><student>
    <CNE>940</CNE>
    <LastName>Esom</LastName>
    <FirstName>Brande</FirstName>
    <DateofBirth>13/08/1998</DateofBirth>
    <Phone>103 255 8071</Phone>
    <Email>relington6h@cargocollective.com</Email>
  </student><student>
    <CNE>941</CNE>
    <LastName>Rymell</LastName>
    <FirstName>Kevyn</FirstName>
    <DateofBirth>24/03/1998</DateofBirth>
    <Phone>643 854 5790</Phone>
    <Email>kskally6i@chicagotribune.com</Email>
  </student><student>
    <CNE>942</CNE>
    <LastName>Cottle</LastName>
    <FirstName>Hobart</FirstName>
    <DateofBirth>07/06/2000</DateofBirth>
    <Phone>589 166 6297</Phone>
    <Email>nbolan6j@over-blog.com</Email>
  </student><student>
    <CNE>943</CNE>
    <LastName>Ibbs</LastName>
    <FirstName>Mickie</FirstName>
    <DateofBirth>18/11/1999</DateofBirth>
    <Phone>810 501 8742</Phone>
    <Email>sfreed6k@ehow.com</Email>
  </student><student>
    <CNE>944</CNE>
    <LastName>Spinozzi</LastName>
    <FirstName>Ted</FirstName>
    <DateofBirth>25/03/2000</DateofBirth>
    <Phone>923 864 6562</Phone>
    <Email>mvanshin6l@geocities.com</Email>
  </student><student>
    <CNE>945</CNE>
    <LastName>Hazeman</LastName>
    <FirstName>Ruthann</FirstName>
    <DateofBirth>20/02/2000</DateofBirth>
    <Phone>599 581 8745</Phone>
    <Email>rhakewell6m@ucoz.com</Email>
  </student><student>
    <CNE>946</CNE>
    <LastName>Sadat</LastName>
    <FirstName>Fleur</FirstName>
    <DateofBirth>06/04/1999</DateofBirth>
    <Phone>471 650 6456</Phone>
    <Email>rgravenall6n@nasa.gov</Email>
  </student></students>

=== lookman6/GestionScolaire-XML-XSLT-XSLFO-XQUERY-XPATH/fichiersXml/listeGroupesXml/liste_AP1_Gr9.xml
<?xml version="1.0"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C://xampp/htdocs/Gestion_scolaire/fichiersDeValidation/students.xsd"><student>
    <CNE>1139</CNE>
    <LastName>Jeffcock</LastName>
    <FirstName>Lillian</FirstName>
    <DateofBirth>19/06/2001</DateofBirth>
    <Phone>937 110 8485</Phone>
    <Email>tliepmann5c@ifeng.com</Email>
  </student><student>
    <CNE>1140</CNE>
    <LastName>Hayller</LastName>
    <FirstName>Belle</FirstName>
    <DateofBirth>24/07/2000</DateofBirth>
    <Phone>219 198 4486</Phone>
    <Email>dbogue5d@umich.edu</Email>
  </student><student>
    <CNE>1141</CNE>
    <LastName>Tibbles</LastName>
    <FirstName>Melony</FirstName>
    <DateofBirth>22/11/1998</DateofBirth>
    <Phone>382 914 8078</Phone>
    <Email>mcalton5e@cdc.gov</Email>
  </student><student>
    <CNE>1142</CNE>
    <LastName>Palfery</LastName>
    <FirstName>Ethan</FirstName>
    <DateofBirth>06/10/1998</DateofBirth>
    <Phone>339 870 6976</Phone>
    <Email>jviles5f@technorati.com</Email>
  </student><student>
    <CNE>1143</CNE>
    <LastName>Corballis</LastName>
    <FirstName>Ida</FirstName>
    <DateofBirth>04/02/1999</DateofBirth>
    <Phone>574 660 0238</Phone>
    <Email>ncasely5g@sogou.com</Email>
  </student><student>
    <CNE>1144</CNE>
    <LastName>Hissie</LastName>
    <FirstName>Homere</FirstName>
    <DateofBirth>30/01/2000</DateofBirth>
    <Phone>147 743 9151</Phone>
    <Email>nspurret5h@nba.com</Email>
  </student><student>
    <CNE>1145</CNE>
    <LastName>Quested</LastName>
    <FirstName>Renaldo</FirstName>
    <DateofBirth>04/02/2000</DateofBirth>
    <Phone>781 240 4778</Phone>
    <Email>ocarlaw5i@sciencedaily.com</Email>
  </student><student>
    <CNE>1146</CNE>
    <LastName>Casin</LastName>
    <FirstName>Hedi</FirstName>
    <DateofBirth>15/11/2001</DateofBirth>
    <Phone>538 317 8365</Phone>
    <Email>aelgie5j@prnewswire.com</Email>
  </student><student>
    <CNE>1147</CNE>
    <LastName>Doe</LastName>
    <FirstName>Mellisent</FirstName>
    <DateofBirth>10/04/1999</DateofBirth>
    <Phone>341 112 2021</Phone>
    <Email>eglossup5k@cornell.edu</Email>
  </student><student>
    <CNE>1148</CNE>
    <LastName>Dunthorn</LastName>
    <FirstName>Camala</FirstName>
    <DateofBirth>31/01/2000</DateofBirth>
    <Phone>163 600 6130</Phone>
    <Email>fjewster5l@answers.com</Email>
  </student><student>
    <CNE>1149</CNE>
    <LastName>Cutriss</LastName>
    <FirstName>Graig</FirstName>
    <DateofBirth>23/05/1999</DateofBirth>
    <Phone>417 717 6189</Phone>
    <Email>gchicco5m@wikia.com</Email>
  </student><student>
    <CNE>1150</CNE>
    <LastName>Syfax</LastName>
    <FirstName>Kevon</FirstName>
    <DateofBirth>03/08/1998</DateofBirth>
    <Phone>806 327 3905</Phone>
    <Email>kteanby5n@a8.net</Email>
  </student><student>
    <CNE>1151</CNE>
    <LastName>Hartburn</LastName>
    <FirstName>Ambur</FirstName>
    <DateofBirth>09/05/1998</DateofBirth>
    <Phone>690 277 9202</Phone>
    <Email>lboyle5o@vkontakte.ru</Email>
  </student><student>
    <CNE>1152</CNE>
    <LastName>Woodall</LastName>
    <FirstName>Ruperta</FirstName>
    <DateofBirth>02/10/2001</DateofBirth>
    <Phone>609 129 5083</Phone>
    <Email>trickman5p@auda.org.au</Email>
  </student><student>
    <CNE>1153</CNE>
    <LastName>MacCambridge</LastName>
    <FirstName>Boone</FirstName>
    <DateofBirth>14/02/2000</DateofBirth>
    <Phone>408 637 6899</Phone>
    <Email>clatimer5q@china.com.cn</Email>
  </student><student>
    <CNE>1154</CNE>
    <LastName>Leng</LastName>
    <FirstName>Cece</FirstName>
    <DateofBirth>19/04/2001</DateofBirth>
    <Phone>298 209 1694</Phone>
    <Email>pradish5r@scientificamerican.com</Email>
  </student><student>
    <CNE>1155</CNE>
    <LastName>McChruiter</LastName>
    <FirstName>Lynelle</FirstName>
    <DateofBirth>12/06/1999</DateofBirth>
    <Phone>533 906 7256</Phone>
    <Email>cgerrit5s@howstuffworks.com</Email>
  </student><student>
    <CNE>1156</CNE>
    <LastName>Braney</LastName>
    <FirstName>Wilone</FirstName>
    <DateofBirth>20/08/1998</DateofBirth>
    <Phone>181 545 9151</Phone>
    <Email>llevitt5t@army.mil</Email>
  </student><student>
    <CNE>1157</CNE>
    <LastName>Satyford</LastName>
    <FirstName>Rica</FirstName>
    <DateofBirth>19/01/1999</DateofBirth>
    <Phone>318 461 8774</Phone>
    <Email>swakely5u@hatena.ne.jp</Email>
  </student><student>
    <CNE>1158</CNE>
    <LastName>Condliffe</LastName>
    <FirstName>Fee</FirstName>
    <DateofBirth>13/08/2001</DateofBirth>
    <Phone>800 619 0050</Phone>
    <Email>bdunford5v@twitpic.com</Email>
  </student><student>
    <CNE>1159</CNE>
    <LastName>Treadwell</LastName>
    <FirstName>Zeb</FirstName>
    <DateofBirth>21/03/1999</DateofBirth>
    <Phone>578 693 7861</Phone>
    <Email>cgreeno5w@marriott.com</Email>
  </student><student>
    <CNE>1160</CNE>
    <LastName>Tanswill</LastName>
    <FirstName>Mandi</FirstName>
    <DateofBirth>28/04/1999</DateofBirth>
    <Phone>461 341 5878</Phone>
    <Email>rduxbury5x@sciencedaily.com</Email>
  </student><student>
    <CNE>1161</CNE>
    <LastName>Fallowfield</LastName>
    <FirstName>Kelcie</FirstName>
    <DateofBirth>13/05/1998</DateofBirth>
    <Phone>829 445 9149</Phone>
    <Email>rderks5y@exblog.jp</Email>
  </student><student>
    <CNE>1162</CNE>
    <LastName>Olrenshaw</LastName>
    <FirstName>Trenna</FirstName>
    <DateofBirth>05/11/1999</DateofBirth>
    <Phone>301 922 6391</Phone>
    <Email>drawkesby5z@barnesandnoble.com</Email>
  </student></students>
